// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: chalkos/node/v1/node.proto

// The API of chalkd, the agent on every chalkos node and on the installer. chalkd serves it on
// TCP port 50000 over TLS; chalkctl is its client.
package nodev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/trevex/chalkos/pkg/api/node/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// NodeServiceName is the fully-qualified name of the NodeService service.
	NodeServiceName = "chalkos.node.v1.NodeService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// NodeServiceInfoProcedure is the fully-qualified name of the NodeService's Info RPC.
	NodeServiceInfoProcedure = "/chalkos.node.v1.NodeService/Info"
	// NodeServiceDisksProcedure is the fully-qualified name of the NodeService's Disks RPC.
	NodeServiceDisksProcedure = "/chalkos.node.v1.NodeService/Disks"
	// NodeServiceInstallProcedure is the fully-qualified name of the NodeService's Install RPC.
	NodeServiceInstallProcedure = "/chalkos.node.v1.NodeService/Install"
	// NodeServiceApplyIdentityProcedure is the fully-qualified name of the NodeService's ApplyIdentity
	// RPC.
	NodeServiceApplyIdentityProcedure = "/chalkos.node.v1.NodeService/ApplyIdentity"
	// NodeServiceResetVolumeProcedure is the fully-qualified name of the NodeService's ResetVolume RPC.
	NodeServiceResetVolumeProcedure = "/chalkos.node.v1.NodeService/ResetVolume"
	// NodeServiceStatusProcedure is the fully-qualified name of the NodeService's Status RPC.
	NodeServiceStatusProcedure = "/chalkos.node.v1.NodeService/Status"
	// NodeServiceLogsProcedure is the fully-qualified name of the NodeService's Logs RPC.
	NodeServiceLogsProcedure = "/chalkos.node.v1.NodeService/Logs"
	// NodeServiceRebootProcedure is the fully-qualified name of the NodeService's Reboot RPC.
	NodeServiceRebootProcedure = "/chalkos.node.v1.NodeService/Reboot"
	// NodeServiceBootstrapProcedure is the fully-qualified name of the NodeService's Bootstrap RPC.
	NodeServiceBootstrapProcedure = "/chalkos.node.v1.NodeService/Bootstrap"
	// NodeServiceEtcdMembersProcedure is the fully-qualified name of the NodeService's EtcdMembers RPC.
	NodeServiceEtcdMembersProcedure = "/chalkos.node.v1.NodeService/EtcdMembers"
	// NodeServiceEtcdRemoveMemberProcedure is the fully-qualified name of the NodeService's
	// EtcdRemoveMember RPC.
	NodeServiceEtcdRemoveMemberProcedure = "/chalkos.node.v1.NodeService/EtcdRemoveMember"
	// NodeServiceEtcdLeaveProcedure is the fully-qualified name of the NodeService's EtcdLeave RPC.
	NodeServiceEtcdLeaveProcedure = "/chalkos.node.v1.NodeService/EtcdLeave"
	// NodeServiceRenewNodeCertificateProcedure is the fully-qualified name of the NodeService's
	// RenewNodeCertificate RPC.
	NodeServiceRenewNodeCertificateProcedure = "/chalkos.node.v1.NodeService/RenewNodeCertificate"
	// NodeServiceRotationStepProcedure is the fully-qualified name of the NodeService's RotationStep
	// RPC.
	NodeServiceRotationStepProcedure = "/chalkos.node.v1.NodeService/RotationStep"
)

// NodeServiceClient is a client for the chalkos.node.v1.NodeService service.
type NodeServiceClient interface {
	// Info describes the node and the agent. Available in both modes to readers.
	Info(context.Context, *connect.Request[v1.InfoRequest]) (*connect.Response[v1.InfoResponse], error)
	// Disks lists the node's disks and their partitions. Available in both modes to readers.
	Disks(context.Context, *connect.Request[v1.DisksRequest]) (*connect.Response[v1.DisksResponse], error)
	// Install turns a node in maintenance mode into an installed node and reboots it. The first
	// message carries the header; image chunks follow when the node is the installer.
	Install(context.Context) *connect.ClientStreamForClient[v1.InstallRequest, v1.InstallResponse]
	// ApplyIdentity replaces the identity of an installed node. Destructive storage changes are
	// refused; additive ones are applied live.
	ApplyIdentity(context.Context, *connect.Request[v1.ApplyIdentityRequest]) (*connect.Response[v1.ApplyIdentityResponse], error)
	// ResetVolume wipes one volume and creates it again as the delivered identity defines it.
	ResetVolume(context.Context, *connect.Request[v1.ResetVolumeRequest]) (*connect.Response[v1.ResetVolumeResponse], error)
	// Status reports the identity version, the storage, and failed units of an installed node.
	Status(context.Context, *connect.Request[v1.StatusRequest]) (*connect.Response[v1.StatusResponse], error)
	// Logs streams the journal of the current boot, or of one unit in it.
	Logs(context.Context, *connect.Request[v1.LogsRequest]) (*connect.ServerStreamForClient[v1.LogsResponse], error)
	// Reboot reboots the node once the response is sent.
	Reboot(context.Context, *connect.Request[v1.RebootRequest]) (*connect.Response[v1.RebootResponse], error)
	// Bootstrap initialises etcd on a control-plane node, starts the control plane and applies
	// the cluster's manifests. It is refused on a node that is bootstrapped or holds etcd data,
	// so no second cluster is ever initialised.
	Bootstrap(context.Context, *connect.Request[v1.BootstrapRequest]) (*connect.Response[v1.BootstrapResponse], error)
	// EtcdMembers lists etcd's members as the node's own member sees them, with their health.
	// Available on control-plane nodes that are etcd members.
	EtcdMembers(context.Context, *connect.Request[v1.EtcdMembersRequest]) (*connect.Response[v1.EtcdMembersResponse], error)
	// EtcdRemoveMember removes another node's etcd member. It is refused when the voters left would
	// have fewer healthy members than their quorum, unless forced.
	EtcdRemoveMember(context.Context, *connect.Request[v1.EtcdRemoveMemberRequest]) (*connect.Response[v1.EtcdRemoveMemberResponse], error)
	// EtcdLeave takes the node out of etcd: it releases the VIPs, removes its own member, if etcd
	// still has it, with the same quorum guard, stops its control plane, deletes its etcd data and
	// unpins its addresses. The node joins the cluster again only once it is reinstalled. A
	// bootstrapped node whose own member does not answer leaves only when forced.
	EtcdLeave(context.Context, *connect.Request[v1.EtcdLeaveRequest]) (*connect.Response[v1.EtcdLeaveResponse], error)
	// RenewNodeCertificate issues the calling node a node certificate from the node CA, for exactly
	// the names of the node certificate it authenticated with. Available on control-plane nodes, to
	// nodes only.
	RenewNodeCertificate(context.Context, *connect.Request[v1.RenewNodeCertificateRequest]) (*connect.Response[v1.RenewNodeCertificateResponse], error)
	// RotationStep runs a step of a CA or key rotation that the node's Kubernetes side carries
	// out; chalkctl rotate calls it. Available to admins.
	RotationStep(context.Context, *connect.Request[v1.RotationStepRequest]) (*connect.Response[v1.RotationStepResponse], error)
}

// NewNodeServiceClient constructs a client for the chalkos.node.v1.NodeService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewNodeServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) NodeServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	nodeServiceMethods := v1.File_chalkos_node_v1_node_proto.Services().ByName("NodeService").Methods()
	return &nodeServiceClient{
		info: connect.NewClient[v1.InfoRequest, v1.InfoResponse](
			httpClient,
			baseURL+NodeServiceInfoProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("Info")),
			connect.WithClientOptions(opts...),
		),
		disks: connect.NewClient[v1.DisksRequest, v1.DisksResponse](
			httpClient,
			baseURL+NodeServiceDisksProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("Disks")),
			connect.WithClientOptions(opts...),
		),
		install: connect.NewClient[v1.InstallRequest, v1.InstallResponse](
			httpClient,
			baseURL+NodeServiceInstallProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("Install")),
			connect.WithClientOptions(opts...),
		),
		applyIdentity: connect.NewClient[v1.ApplyIdentityRequest, v1.ApplyIdentityResponse](
			httpClient,
			baseURL+NodeServiceApplyIdentityProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("ApplyIdentity")),
			connect.WithClientOptions(opts...),
		),
		resetVolume: connect.NewClient[v1.ResetVolumeRequest, v1.ResetVolumeResponse](
			httpClient,
			baseURL+NodeServiceResetVolumeProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("ResetVolume")),
			connect.WithClientOptions(opts...),
		),
		status: connect.NewClient[v1.StatusRequest, v1.StatusResponse](
			httpClient,
			baseURL+NodeServiceStatusProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("Status")),
			connect.WithClientOptions(opts...),
		),
		logs: connect.NewClient[v1.LogsRequest, v1.LogsResponse](
			httpClient,
			baseURL+NodeServiceLogsProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("Logs")),
			connect.WithClientOptions(opts...),
		),
		reboot: connect.NewClient[v1.RebootRequest, v1.RebootResponse](
			httpClient,
			baseURL+NodeServiceRebootProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("Reboot")),
			connect.WithClientOptions(opts...),
		),
		bootstrap: connect.NewClient[v1.BootstrapRequest, v1.BootstrapResponse](
			httpClient,
			baseURL+NodeServiceBootstrapProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("Bootstrap")),
			connect.WithClientOptions(opts...),
		),
		etcdMembers: connect.NewClient[v1.EtcdMembersRequest, v1.EtcdMembersResponse](
			httpClient,
			baseURL+NodeServiceEtcdMembersProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("EtcdMembers")),
			connect.WithClientOptions(opts...),
		),
		etcdRemoveMember: connect.NewClient[v1.EtcdRemoveMemberRequest, v1.EtcdRemoveMemberResponse](
			httpClient,
			baseURL+NodeServiceEtcdRemoveMemberProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("EtcdRemoveMember")),
			connect.WithClientOptions(opts...),
		),
		etcdLeave: connect.NewClient[v1.EtcdLeaveRequest, v1.EtcdLeaveResponse](
			httpClient,
			baseURL+NodeServiceEtcdLeaveProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("EtcdLeave")),
			connect.WithClientOptions(opts...),
		),
		renewNodeCertificate: connect.NewClient[v1.RenewNodeCertificateRequest, v1.RenewNodeCertificateResponse](
			httpClient,
			baseURL+NodeServiceRenewNodeCertificateProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("RenewNodeCertificate")),
			connect.WithClientOptions(opts...),
		),
		rotationStep: connect.NewClient[v1.RotationStepRequest, v1.RotationStepResponse](
			httpClient,
			baseURL+NodeServiceRotationStepProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("RotationStep")),
			connect.WithClientOptions(opts...),
		),
	}
}

// nodeServiceClient implements NodeServiceClient.
type nodeServiceClient struct {
	info                 *connect.Client[v1.InfoRequest, v1.InfoResponse]
	disks                *connect.Client[v1.DisksRequest, v1.DisksResponse]
	install              *connect.Client[v1.InstallRequest, v1.InstallResponse]
	applyIdentity        *connect.Client[v1.ApplyIdentityRequest, v1.ApplyIdentityResponse]
	resetVolume          *connect.Client[v1.ResetVolumeRequest, v1.ResetVolumeResponse]
	status               *connect.Client[v1.StatusRequest, v1.StatusResponse]
	logs                 *connect.Client[v1.LogsRequest, v1.LogsResponse]
	reboot               *connect.Client[v1.RebootRequest, v1.RebootResponse]
	bootstrap            *connect.Client[v1.BootstrapRequest, v1.BootstrapResponse]
	etcdMembers          *connect.Client[v1.EtcdMembersRequest, v1.EtcdMembersResponse]
	etcdRemoveMember     *connect.Client[v1.EtcdRemoveMemberRequest, v1.EtcdRemoveMemberResponse]
	etcdLeave            *connect.Client[v1.EtcdLeaveRequest, v1.EtcdLeaveResponse]
	renewNodeCertificate *connect.Client[v1.RenewNodeCertificateRequest, v1.RenewNodeCertificateResponse]
	rotationStep         *connect.Client[v1.RotationStepRequest, v1.RotationStepResponse]
}

// Info calls chalkos.node.v1.NodeService.Info.
func (c *nodeServiceClient) Info(ctx context.Context, req *connect.Request[v1.InfoRequest]) (*connect.Response[v1.InfoResponse], error) {
	return c.info.CallUnary(ctx, req)
}

// Disks calls chalkos.node.v1.NodeService.Disks.
func (c *nodeServiceClient) Disks(ctx context.Context, req *connect.Request[v1.DisksRequest]) (*connect.Response[v1.DisksResponse], error) {
	return c.disks.CallUnary(ctx, req)
}

// Install calls chalkos.node.v1.NodeService.Install.
func (c *nodeServiceClient) Install(ctx context.Context) *connect.ClientStreamForClient[v1.InstallRequest, v1.InstallResponse] {
	return c.install.CallClientStream(ctx)
}

// ApplyIdentity calls chalkos.node.v1.NodeService.ApplyIdentity.
func (c *nodeServiceClient) ApplyIdentity(ctx context.Context, req *connect.Request[v1.ApplyIdentityRequest]) (*connect.Response[v1.ApplyIdentityResponse], error) {
	return c.applyIdentity.CallUnary(ctx, req)
}

// ResetVolume calls chalkos.node.v1.NodeService.ResetVolume.
func (c *nodeServiceClient) ResetVolume(ctx context.Context, req *connect.Request[v1.ResetVolumeRequest]) (*connect.Response[v1.ResetVolumeResponse], error) {
	return c.resetVolume.CallUnary(ctx, req)
}

// Status calls chalkos.node.v1.NodeService.Status.
func (c *nodeServiceClient) Status(ctx context.Context, req *connect.Request[v1.StatusRequest]) (*connect.Response[v1.StatusResponse], error) {
	return c.status.CallUnary(ctx, req)
}

// Logs calls chalkos.node.v1.NodeService.Logs.
func (c *nodeServiceClient) Logs(ctx context.Context, req *connect.Request[v1.LogsRequest]) (*connect.ServerStreamForClient[v1.LogsResponse], error) {
	return c.logs.CallServerStream(ctx, req)
}

// Reboot calls chalkos.node.v1.NodeService.Reboot.
func (c *nodeServiceClient) Reboot(ctx context.Context, req *connect.Request[v1.RebootRequest]) (*connect.Response[v1.RebootResponse], error) {
	return c.reboot.CallUnary(ctx, req)
}

// Bootstrap calls chalkos.node.v1.NodeService.Bootstrap.
func (c *nodeServiceClient) Bootstrap(ctx context.Context, req *connect.Request[v1.BootstrapRequest]) (*connect.Response[v1.BootstrapResponse], error) {
	return c.bootstrap.CallUnary(ctx, req)
}

// EtcdMembers calls chalkos.node.v1.NodeService.EtcdMembers.
func (c *nodeServiceClient) EtcdMembers(ctx context.Context, req *connect.Request[v1.EtcdMembersRequest]) (*connect.Response[v1.EtcdMembersResponse], error) {
	return c.etcdMembers.CallUnary(ctx, req)
}

// EtcdRemoveMember calls chalkos.node.v1.NodeService.EtcdRemoveMember.
func (c *nodeServiceClient) EtcdRemoveMember(ctx context.Context, req *connect.Request[v1.EtcdRemoveMemberRequest]) (*connect.Response[v1.EtcdRemoveMemberResponse], error) {
	return c.etcdRemoveMember.CallUnary(ctx, req)
}

// EtcdLeave calls chalkos.node.v1.NodeService.EtcdLeave.
func (c *nodeServiceClient) EtcdLeave(ctx context.Context, req *connect.Request[v1.EtcdLeaveRequest]) (*connect.Response[v1.EtcdLeaveResponse], error) {
	return c.etcdLeave.CallUnary(ctx, req)
}

// RenewNodeCertificate calls chalkos.node.v1.NodeService.RenewNodeCertificate.
func (c *nodeServiceClient) RenewNodeCertificate(ctx context.Context, req *connect.Request[v1.RenewNodeCertificateRequest]) (*connect.Response[v1.RenewNodeCertificateResponse], error) {
	return c.renewNodeCertificate.CallUnary(ctx, req)
}

// RotationStep calls chalkos.node.v1.NodeService.RotationStep.
func (c *nodeServiceClient) RotationStep(ctx context.Context, req *connect.Request[v1.RotationStepRequest]) (*connect.Response[v1.RotationStepResponse], error) {
	return c.rotationStep.CallUnary(ctx, req)
}

// NodeServiceHandler is an implementation of the chalkos.node.v1.NodeService service.
type NodeServiceHandler interface {
	// Info describes the node and the agent. Available in both modes to readers.
	Info(context.Context, *connect.Request[v1.InfoRequest]) (*connect.Response[v1.InfoResponse], error)
	// Disks lists the node's disks and their partitions. Available in both modes to readers.
	Disks(context.Context, *connect.Request[v1.DisksRequest]) (*connect.Response[v1.DisksResponse], error)
	// Install turns a node in maintenance mode into an installed node and reboots it. The first
	// message carries the header; image chunks follow when the node is the installer.
	Install(context.Context, *connect.ClientStream[v1.InstallRequest]) (*connect.Response[v1.InstallResponse], error)
	// ApplyIdentity replaces the identity of an installed node. Destructive storage changes are
	// refused; additive ones are applied live.
	ApplyIdentity(context.Context, *connect.Request[v1.ApplyIdentityRequest]) (*connect.Response[v1.ApplyIdentityResponse], error)
	// ResetVolume wipes one volume and creates it again as the delivered identity defines it.
	ResetVolume(context.Context, *connect.Request[v1.ResetVolumeRequest]) (*connect.Response[v1.ResetVolumeResponse], error)
	// Status reports the identity version, the storage, and failed units of an installed node.
	Status(context.Context, *connect.Request[v1.StatusRequest]) (*connect.Response[v1.StatusResponse], error)
	// Logs streams the journal of the current boot, or of one unit in it.
	Logs(context.Context, *connect.Request[v1.LogsRequest], *connect.ServerStream[v1.LogsResponse]) error
	// Reboot reboots the node once the response is sent.
	Reboot(context.Context, *connect.Request[v1.RebootRequest]) (*connect.Response[v1.RebootResponse], error)
	// Bootstrap initialises etcd on a control-plane node, starts the control plane and applies
	// the cluster's manifests. It is refused on a node that is bootstrapped or holds etcd data,
	// so no second cluster is ever initialised.
	Bootstrap(context.Context, *connect.Request[v1.BootstrapRequest]) (*connect.Response[v1.BootstrapResponse], error)
	// EtcdMembers lists etcd's members as the node's own member sees them, with their health.
	// Available on control-plane nodes that are etcd members.
	EtcdMembers(context.Context, *connect.Request[v1.EtcdMembersRequest]) (*connect.Response[v1.EtcdMembersResponse], error)
	// EtcdRemoveMember removes another node's etcd member. It is refused when the voters left would
	// have fewer healthy members than their quorum, unless forced.
	EtcdRemoveMember(context.Context, *connect.Request[v1.EtcdRemoveMemberRequest]) (*connect.Response[v1.EtcdRemoveMemberResponse], error)
	// EtcdLeave takes the node out of etcd: it releases the VIPs, removes its own member, if etcd
	// still has it, with the same quorum guard, stops its control plane, deletes its etcd data and
	// unpins its addresses. The node joins the cluster again only once it is reinstalled. A
	// bootstrapped node whose own member does not answer leaves only when forced.
	EtcdLeave(context.Context, *connect.Request[v1.EtcdLeaveRequest]) (*connect.Response[v1.EtcdLeaveResponse], error)
	// RenewNodeCertificate issues the calling node a node certificate from the node CA, for exactly
	// the names of the node certificate it authenticated with. Available on control-plane nodes, to
	// nodes only.
	RenewNodeCertificate(context.Context, *connect.Request[v1.RenewNodeCertificateRequest]) (*connect.Response[v1.RenewNodeCertificateResponse], error)
	// RotationStep runs a step of a CA or key rotation that the node's Kubernetes side carries
	// out; chalkctl rotate calls it. Available to admins.
	RotationStep(context.Context, *connect.Request[v1.RotationStepRequest]) (*connect.Response[v1.RotationStepResponse], error)
}

// NewNodeServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewNodeServiceHandler(svc NodeServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	nodeServiceMethods := v1.File_chalkos_node_v1_node_proto.Services().ByName("NodeService").Methods()
	nodeServiceInfoHandler := connect.NewUnaryHandler(
		NodeServiceInfoProcedure,
		svc.Info,
		connect.WithSchema(nodeServiceMethods.ByName("Info")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceDisksHandler := connect.NewUnaryHandler(
		NodeServiceDisksProcedure,
		svc.Disks,
		connect.WithSchema(nodeServiceMethods.ByName("Disks")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceInstallHandler := connect.NewClientStreamHandler(
		NodeServiceInstallProcedure,
		svc.Install,
		connect.WithSchema(nodeServiceMethods.ByName("Install")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceApplyIdentityHandler := connect.NewUnaryHandler(
		NodeServiceApplyIdentityProcedure,
		svc.ApplyIdentity,
		connect.WithSchema(nodeServiceMethods.ByName("ApplyIdentity")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceResetVolumeHandler := connect.NewUnaryHandler(
		NodeServiceResetVolumeProcedure,
		svc.ResetVolume,
		connect.WithSchema(nodeServiceMethods.ByName("ResetVolume")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceStatusHandler := connect.NewUnaryHandler(
		NodeServiceStatusProcedure,
		svc.Status,
		connect.WithSchema(nodeServiceMethods.ByName("Status")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceLogsHandler := connect.NewServerStreamHandler(
		NodeServiceLogsProcedure,
		svc.Logs,
		connect.WithSchema(nodeServiceMethods.ByName("Logs")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceRebootHandler := connect.NewUnaryHandler(
		NodeServiceRebootProcedure,
		svc.Reboot,
		connect.WithSchema(nodeServiceMethods.ByName("Reboot")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceBootstrapHandler := connect.NewUnaryHandler(
		NodeServiceBootstrapProcedure,
		svc.Bootstrap,
		connect.WithSchema(nodeServiceMethods.ByName("Bootstrap")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceEtcdMembersHandler := connect.NewUnaryHandler(
		NodeServiceEtcdMembersProcedure,
		svc.EtcdMembers,
		connect.WithSchema(nodeServiceMethods.ByName("EtcdMembers")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceEtcdRemoveMemberHandler := connect.NewUnaryHandler(
		NodeServiceEtcdRemoveMemberProcedure,
		svc.EtcdRemoveMember,
		connect.WithSchema(nodeServiceMethods.ByName("EtcdRemoveMember")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceEtcdLeaveHandler := connect.NewUnaryHandler(
		NodeServiceEtcdLeaveProcedure,
		svc.EtcdLeave,
		connect.WithSchema(nodeServiceMethods.ByName("EtcdLeave")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceRenewNodeCertificateHandler := connect.NewUnaryHandler(
		NodeServiceRenewNodeCertificateProcedure,
		svc.RenewNodeCertificate,
		connect.WithSchema(nodeServiceMethods.ByName("RenewNodeCertificate")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceRotationStepHandler := connect.NewUnaryHandler(
		NodeServiceRotationStepProcedure,
		svc.RotationStep,
		connect.WithSchema(nodeServiceMethods.ByName("RotationStep")),
		connect.WithHandlerOptions(opts...),
	)
	return "/chalkos.node.v1.NodeService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case NodeServiceInfoProcedure:
			nodeServiceInfoHandler.ServeHTTP(w, r)
		case NodeServiceDisksProcedure:
			nodeServiceDisksHandler.ServeHTTP(w, r)
		case NodeServiceInstallProcedure:
			nodeServiceInstallHandler.ServeHTTP(w, r)
		case NodeServiceApplyIdentityProcedure:
			nodeServiceApplyIdentityHandler.ServeHTTP(w, r)
		case NodeServiceResetVolumeProcedure:
			nodeServiceResetVolumeHandler.ServeHTTP(w, r)
		case NodeServiceStatusProcedure:
			nodeServiceStatusHandler.ServeHTTP(w, r)
		case NodeServiceLogsProcedure:
			nodeServiceLogsHandler.ServeHTTP(w, r)
		case NodeServiceRebootProcedure:
			nodeServiceRebootHandler.ServeHTTP(w, r)
		case NodeServiceBootstrapProcedure:
			nodeServiceBootstrapHandler.ServeHTTP(w, r)
		case NodeServiceEtcdMembersProcedure:
			nodeServiceEtcdMembersHandler.ServeHTTP(w, r)
		case NodeServiceEtcdRemoveMemberProcedure:
			nodeServiceEtcdRemoveMemberHandler.ServeHTTP(w, r)
		case NodeServiceEtcdLeaveProcedure:
			nodeServiceEtcdLeaveHandler.ServeHTTP(w, r)
		case NodeServiceRenewNodeCertificateProcedure:
			nodeServiceRenewNodeCertificateHandler.ServeHTTP(w, r)
		case NodeServiceRotationStepProcedure:
			nodeServiceRotationStepHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedNodeServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedNodeServiceHandler struct{}

func (UnimplementedNodeServiceHandler) Info(context.Context, *connect.Request[v1.InfoRequest]) (*connect.Response[v1.InfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chalkos.node.v1.NodeService.Info is not implemented"))
}

func (UnimplementedNodeServiceHandler) Disks(context.Context, *connect.Request[v1.DisksRequest]) (*connect.Response[v1.DisksResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chalkos.node.v1.NodeService.Disks is not implemented"))
}

func (UnimplementedNodeServiceHandler) Install(context.Context, *connect.ClientStream[v1.InstallRequest]) (*connect.Response[v1.InstallResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chalkos.node.v1.NodeService.Install is not implemented"))
}

func (UnimplementedNodeServiceHandler) ApplyIdentity(context.Context, *connect.Request[v1.ApplyIdentityRequest]) (*connect.Response[v1.ApplyIdentityResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chalkos.node.v1.NodeService.ApplyIdentity is not implemented"))
}

func (UnimplementedNodeServiceHandler) ResetVolume(context.Context, *connect.Request[v1.ResetVolumeRequest]) (*connect.Response[v1.ResetVolumeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chalkos.node.v1.NodeService.ResetVolume is not implemented"))
}

func (UnimplementedNodeServiceHandler) Status(context.Context, *connect.Request[v1.StatusRequest]) (*connect.Response[v1.StatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chalkos.node.v1.NodeService.Status is not implemented"))
}

func (UnimplementedNodeServiceHandler) Logs(context.Context, *connect.Request[v1.LogsRequest], *connect.ServerStream[v1.LogsResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("chalkos.node.v1.NodeService.Logs is not implemented"))
}

func (UnimplementedNodeServiceHandler) Reboot(context.Context, *connect.Request[v1.RebootRequest]) (*connect.Response[v1.RebootResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chalkos.node.v1.NodeService.Reboot is not implemented"))
}

func (UnimplementedNodeServiceHandler) Bootstrap(context.Context, *connect.Request[v1.BootstrapRequest]) (*connect.Response[v1.BootstrapResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chalkos.node.v1.NodeService.Bootstrap is not implemented"))
}

func (UnimplementedNodeServiceHandler) EtcdMembers(context.Context, *connect.Request[v1.EtcdMembersRequest]) (*connect.Response[v1.EtcdMembersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chalkos.node.v1.NodeService.EtcdMembers is not implemented"))
}

func (UnimplementedNodeServiceHandler) EtcdRemoveMember(context.Context, *connect.Request[v1.EtcdRemoveMemberRequest]) (*connect.Response[v1.EtcdRemoveMemberResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chalkos.node.v1.NodeService.EtcdRemoveMember is not implemented"))
}

func (UnimplementedNodeServiceHandler) EtcdLeave(context.Context, *connect.Request[v1.EtcdLeaveRequest]) (*connect.Response[v1.EtcdLeaveResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chalkos.node.v1.NodeService.EtcdLeave is not implemented"))
}

func (UnimplementedNodeServiceHandler) RenewNodeCertificate(context.Context, *connect.Request[v1.RenewNodeCertificateRequest]) (*connect.Response[v1.RenewNodeCertificateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chalkos.node.v1.NodeService.RenewNodeCertificate is not implemented"))
}

func (UnimplementedNodeServiceHandler) RotationStep(context.Context, *connect.Request[v1.RotationStepRequest]) (*connect.Response[v1.RotationStepResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chalkos.node.v1.NodeService.RotationStep is not implemented"))
}
