// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: chalkos/node/v1/node.proto

// The API of chalkd, the agent on every chalkos node and on the installer. chalkd serves it on
// TCP port 50000 over TLS; chalkctl is its client.

package nodev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Mode int32

const (
	Mode_MODE_UNSPECIFIED Mode = 0
	// The node is not installed: chalkd serves a self-signed certificate.
	Mode_MODE_MAINTENANCE Mode = 1
	// The node is installed: chalkd serves its node certificate and requires client certificates.
	Mode_MODE_NORMAL Mode = 2
)

// Enum value maps for Mode.
var (
	Mode_name = map[int32]string{
		0: "MODE_UNSPECIFIED",
		1: "MODE_MAINTENANCE",
		2: "MODE_NORMAL",
	}
	Mode_value = map[string]int32{
		"MODE_UNSPECIFIED": 0,
		"MODE_MAINTENANCE": 1,
		"MODE_NORMAL":      2,
	}
)

func (x Mode) Enum() *Mode {
	p := new(Mode)
	*p = x
	return p
}

func (x Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_chalkos_node_v1_node_proto_enumTypes[0].Descriptor()
}

func (Mode) Type() protoreflect.EnumType {
	return &file_chalkos_node_v1_node_proto_enumTypes[0]
}

func (x Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Mode.Descriptor instead.
func (Mode) EnumDescriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{0}
}

type SecureBoot int32

const (
	SecureBoot_SECURE_BOOT_UNSPECIFIED SecureBoot = 0
	SecureBoot_SECURE_BOOT_DISABLED    SecureBoot = 1
	SecureBoot_SECURE_BOOT_ENABLED     SecureBoot = 2
	// The firmware accepts new Secure Boot keys without authentication.
	SecureBoot_SECURE_BOOT_SETUP_MODE SecureBoot = 3
)

// Enum value maps for SecureBoot.
var (
	SecureBoot_name = map[int32]string{
		0: "SECURE_BOOT_UNSPECIFIED",
		1: "SECURE_BOOT_DISABLED",
		2: "SECURE_BOOT_ENABLED",
		3: "SECURE_BOOT_SETUP_MODE",
	}
	SecureBoot_value = map[string]int32{
		"SECURE_BOOT_UNSPECIFIED": 0,
		"SECURE_BOOT_DISABLED":    1,
		"SECURE_BOOT_ENABLED":     2,
		"SECURE_BOOT_SETUP_MODE":  3,
	}
)

func (x SecureBoot) Enum() *SecureBoot {
	p := new(SecureBoot)
	*p = x
	return p
}

func (x SecureBoot) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecureBoot) Descriptor() protoreflect.EnumDescriptor {
	return file_chalkos_node_v1_node_proto_enumTypes[1].Descriptor()
}

func (SecureBoot) Type() protoreflect.EnumType {
	return &file_chalkos_node_v1_node_proto_enumTypes[1]
}

func (x SecureBoot) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SecureBoot.Descriptor instead.
func (SecureBoot) EnumDescriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{1}
}

type InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{0}
}

type InfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Mode  Mode                   `protobuf:"varint,1,opt,name=mode,proto3,enum=chalkos.node.v1.Mode" json:"mode,omitempty"`
	// chalkos version of the running image.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Image ID of the running image, such as "chalkos".
	ImageId string `protobuf:"bytes,3,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	// Whether the node runs the installer, which writes a role image to another disk.
	Installer bool `protobuf:"varint,4,opt,name=installer,proto3" json:"installer,omitempty"`
	// Device of the disk the node booted from; empty on the installer booted from a CD.
	BootDisk   string     `protobuf:"bytes,5,opt,name=boot_disk,json=bootDisk,proto3" json:"boot_disk,omitempty"`
	Tpm        bool       `protobuf:"varint,6,opt,name=tpm,proto3" json:"tpm,omitempty"`
	SecureBoot SecureBoot `protobuf:"varint,7,opt,name=secure_boot,json=secureBoot,proto3,enum=chalkos.node.v1.SecureBoot" json:"secure_boot,omitempty"`
	// SHA-256 of the certificate chalkd serves, in lower-case hex.
	Fingerprint   string `protobuf:"bytes,8,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	Hostname      string `protobuf:"bytes,9,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{1}
}

func (x *InfoResponse) GetMode() Mode {
	if x != nil {
		return x.Mode
	}
	return Mode_MODE_UNSPECIFIED
}

func (x *InfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InfoResponse) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *InfoResponse) GetInstaller() bool {
	if x != nil {
		return x.Installer
	}
	return false
}

func (x *InfoResponse) GetBootDisk() string {
	if x != nil {
		return x.BootDisk
	}
	return ""
}

func (x *InfoResponse) GetTpm() bool {
	if x != nil {
		return x.Tpm
	}
	return false
}

func (x *InfoResponse) GetSecureBoot() SecureBoot {
	if x != nil {
		return x.SecureBoot
	}
	return SecureBoot_SECURE_BOOT_UNSPECIFIED
}

func (x *InfoResponse) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *InfoResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type DisksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisksRequest) Reset() {
	*x = DisksRequest{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisksRequest) ProtoMessage() {}

func (x *DisksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisksRequest.ProtoReflect.Descriptor instead.
func (*DisksRequest) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{2}
}

type DisksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Disks         []*Disk                `protobuf:"bytes,1,rep,name=disks,proto3" json:"disks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisksResponse) Reset() {
	*x = DisksResponse{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisksResponse) ProtoMessage() {}

func (x *DisksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisksResponse.ProtoReflect.Descriptor instead.
func (*DisksResponse) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{3}
}

func (x *DisksResponse) GetDisks() []*Disk {
	if x != nil {
		return x.Disks
	}
	return nil
}

type Disk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Kernel name, such as nvme0n1.
	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Device string `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	Model  string `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Size   uint64 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Serial string `protobuf:"bytes,5,opt,name=serial,proto3" json:"serial,omitempty"`
	Wwn    string `protobuf:"bytes,6,opt,name=wwn,proto3" json:"wwn,omitempty"`
	// nvme, ssd or hdd.
	Type string `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	// udev's ID_PATH.
	Path       string       `protobuf:"bytes,8,opt,name=path,proto3" json:"path,omitempty"`
	Partitions []*Partition `protobuf:"bytes,9,rep,name=partitions,proto3" json:"partitions,omitempty"`
	// How chalkos uses the disk: "boot" for the boot disk, "disk <name>" for a pinned disk of the
	// node's storage, empty when chalkos does not use it.
	Usage         string `protobuf:"bytes,10,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Disk) Reset() {
	*x = Disk{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Disk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disk) ProtoMessage() {}

func (x *Disk) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disk.ProtoReflect.Descriptor instead.
func (*Disk) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{4}
}

func (x *Disk) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Disk) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *Disk) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Disk) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Disk) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *Disk) GetWwn() string {
	if x != nil {
		return x.Wwn
	}
	return ""
}

func (x *Disk) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Disk) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Disk) GetPartitions() []*Partition {
	if x != nil {
		return x.Partitions
	}
	return nil
}

func (x *Disk) GetUsage() string {
	if x != nil {
		return x.Usage
	}
	return ""
}

type Partition struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Device string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	Number uint32                 `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	Size   uint64                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	// GPT partition type UUID.
	Type  string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Label string `protobuf:"bytes,5,opt,name=label,proto3" json:"label,omitempty"`
	Uuid  string `protobuf:"bytes,6,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// File system or other content blkid found, such as ext4 or crypto_LUKS.
	Content       string `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Partition) Reset() {
	*x = Partition{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Partition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Partition) ProtoMessage() {}

func (x *Partition) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Partition.ProtoReflect.Descriptor instead.
func (*Partition) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{5}
}

func (x *Partition) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *Partition) GetNumber() uint32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Partition) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Partition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Partition) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Partition) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Partition) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type InstallRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*InstallRequest_Header
	//	*InstallRequest_Chunk
	Message       isInstallRequest_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallRequest) Reset() {
	*x = InstallRequest{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallRequest) ProtoMessage() {}

func (x *InstallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallRequest.ProtoReflect.Descriptor instead.
func (*InstallRequest) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{6}
}

func (x *InstallRequest) GetMessage() isInstallRequest_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *InstallRequest) GetHeader() *InstallHeader {
	if x != nil {
		if x, ok := x.Message.(*InstallRequest_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *InstallRequest) GetChunk() *ImageChunk {
	if x != nil {
		if x, ok := x.Message.(*InstallRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isInstallRequest_Message interface {
	isInstallRequest_Message()
}

type InstallRequest_Header struct {
	Header *InstallHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type InstallRequest_Chunk struct {
	Chunk *ImageChunk `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*InstallRequest_Header) isInstallRequest_Message() {}

func (*InstallRequest_Chunk) isInstallRequest_Message() {}

type InstallHeader struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The node's identity as the manifest renders it (JSON), including its storage section.
	Identity string `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	// PEM certificate and key chalkd serves once the node is installed.
	NodeCertificate []byte `protobuf:"bytes,2,opt,name=node_certificate,json=nodeCertificate,proto3" json:"node_certificate,omitempty"`
	NodeKey         []byte `protobuf:"bytes,3,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
	// PEM certificates of the OS CAs the node trusts, the one that issues client certificates and
	// the node CA first, then those still trusted while it rotates.
	CaCertificate []byte `protobuf:"bytes,4,opt,name=ca_certificate,json=caCertificate,proto3" json:"ca_certificate,omitempty"`
	// Recovery key or password enrolled as the second keyslot of every encrypted volume; empty
	// when the node's fallback is none.
	FallbackSecret string `protobuf:"bytes,5,opt,name=fallback_secret,json=fallbackSecret,proto3" json:"fallback_secret,omitempty"`
	// Types that are valid to be assigned to Target:
	//
	//	*InstallHeader_InPlace
	//	*InstallHeader_Disk
	Target isInstallHeader_Target `protobuf_oneof:"target"`
	// Size and SHA-256 of the streamed image; installer only.
	ImageSize   uint64 `protobuf:"varint,8,opt,name=image_size,json=imageSize,proto3" json:"image_size,omitempty"`
	ImageSha256 []byte `protobuf:"bytes,9,opt,name=image_sha256,json=imageSha256,proto3" json:"image_sha256,omitempty"`
	// Let the installer overwrite a target disk that carries data other than chalkos partitions.
	WipeDisk bool `protobuf:"varint,10,opt,name=wipe_disk,json=wipeDisk,proto3" json:"wipe_disk,omitempty"`
	// The role image's repart definitions of the system region (slot B, STATE) by file name;
	// installer only. Each role chooses its partition sizes, so the installer's own may not fit.
	SystemDefinitions map[string]string `protobuf:"bytes,11,rep,name=system_definitions,json=systemDefinitions,proto3" json:"system_definitions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The node's Kubernetes share (JSON): the CAs and keys for a control-plane node, the CA
	// certificate and a kubelet client certificate for a worker. Empty for a role without
	// Kubernetes.
	KubernetesShare []byte `protobuf:"bytes,12,opt,name=kubernetes_share,json=kubernetesShare,proto3" json:"kubernetes_share,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InstallHeader) Reset() {
	*x = InstallHeader{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallHeader) ProtoMessage() {}

func (x *InstallHeader) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallHeader.ProtoReflect.Descriptor instead.
func (*InstallHeader) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{7}
}

func (x *InstallHeader) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *InstallHeader) GetNodeCertificate() []byte {
	if x != nil {
		return x.NodeCertificate
	}
	return nil
}

func (x *InstallHeader) GetNodeKey() []byte {
	if x != nil {
		return x.NodeKey
	}
	return nil
}

func (x *InstallHeader) GetCaCertificate() []byte {
	if x != nil {
		return x.CaCertificate
	}
	return nil
}

func (x *InstallHeader) GetFallbackSecret() string {
	if x != nil {
		return x.FallbackSecret
	}
	return ""
}

func (x *InstallHeader) GetTarget() isInstallHeader_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *InstallHeader) GetInPlace() *InPlace {
	if x != nil {
		if x, ok := x.Target.(*InstallHeader_InPlace); ok {
			return x.InPlace
		}
	}
	return nil
}

func (x *InstallHeader) GetDisk() *DiskReference {
	if x != nil {
		if x, ok := x.Target.(*InstallHeader_Disk); ok {
			return x.Disk
		}
	}
	return nil
}

func (x *InstallHeader) GetImageSize() uint64 {
	if x != nil {
		return x.ImageSize
	}
	return 0
}

func (x *InstallHeader) GetImageSha256() []byte {
	if x != nil {
		return x.ImageSha256
	}
	return nil
}

func (x *InstallHeader) GetWipeDisk() bool {
	if x != nil {
		return x.WipeDisk
	}
	return false
}

func (x *InstallHeader) GetSystemDefinitions() map[string]string {
	if x != nil {
		return x.SystemDefinitions
	}
	return nil
}

func (x *InstallHeader) GetKubernetesShare() []byte {
	if x != nil {
		return x.KubernetesShare
	}
	return nil
}

type isInstallHeader_Target interface {
	isInstallHeader_Target()
}

type InstallHeader_InPlace struct {
	// The role image already runs from the boot disk.
	InPlace *InPlace `protobuf:"bytes,6,opt,name=in_place,json=inPlace,proto3,oneof"`
}

type InstallHeader_Disk struct {
	// The installer writes the streamed image to this disk.
	Disk *DiskReference `protobuf:"bytes,7,opt,name=disk,proto3,oneof"`
}

func (*InstallHeader_InPlace) isInstallHeader_Target() {}

func (*InstallHeader_Disk) isInstallHeader_Target() {}

type InPlace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InPlace) Reset() {
	*x = InPlace{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InPlace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InPlace) ProtoMessage() {}

func (x *InPlace) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InPlace.ProtoReflect.Descriptor instead.
func (*InPlace) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{8}
}

// A disk by /dev path, or by a selector whose set fields must all match.
type DiskReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Serial        string                 `protobuf:"bytes,3,opt,name=serial,proto3" json:"serial,omitempty"`
	Wwn           string                 `protobuf:"bytes,4,opt,name=wwn,proto3" json:"wwn,omitempty"`
	Size          string                 `protobuf:"bytes,5,opt,name=size,proto3" json:"size,omitempty"`
	Type          string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskReference) Reset() {
	*x = DiskReference{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskReference) ProtoMessage() {}

func (x *DiskReference) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskReference.ProtoReflect.Descriptor instead.
func (*DiskReference) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{9}
}

func (x *DiskReference) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DiskReference) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *DiskReference) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *DiskReference) GetWwn() string {
	if x != nil {
		return x.Wwn
	}
	return ""
}

func (x *DiskReference) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *DiskReference) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ImageChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageChunk) Reset() {
	*x = ImageChunk{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageChunk) ProtoMessage() {}

func (x *ImageChunk) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageChunk.ProtoReflect.Descriptor instead.
func (*ImageChunk) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{10}
}

func (x *ImageChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type InstallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallResponse) Reset() {
	*x = InstallResponse{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallResponse) ProtoMessage() {}

func (x *InstallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallResponse.ProtoReflect.Descriptor instead.
func (*InstallResponse) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{11}
}

type ApplyIdentityRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The node's identity as the manifest renders it (JSON); empty keeps the node's identity and
	// storage, for a request that delivers only a share or a node certificate.
	Identity string `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	// Enrolled on encrypted volumes the identity adds; required when it adds one and the node's
	// fallback is not none.
	FallbackSecret string `protobuf:"bytes,2,opt,name=fallback_secret,json=fallbackSecret,proto3" json:"fallback_secret,omitempty"`
	// A new Kubernetes share (JSON) replacing the node's, as InstallHeader carries it; empty
	// keeps the node's share.
	KubernetesShare []byte `protobuf:"bytes,3,opt,name=kubernetes_share,json=kubernetesShare,proto3" json:"kubernetes_share,omitempty"`
	// A new node certificate for the node, followed by the certificate of the node CA that issued
	// it (PEM), and its key, which chalkd serves from then on; empty keeps the node's.
	NodeCertificate []byte `protobuf:"bytes,4,opt,name=node_certificate,json=nodeCertificate,proto3" json:"node_certificate,omitempty"`
	NodeKey         []byte `protobuf:"bytes,5,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
	// The OS CAs the node trusts from now on (PEM), as InstallHeader.ca_certificate holds them;
	// empty keeps the node's. They must verify the node's certificate, the caller's and a control
	// plane's node CA. Not together with a node certificate.
	Trust         []byte `protobuf:"bytes,6,opt,name=trust,proto3" json:"trust,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyIdentityRequest) Reset() {
	*x = ApplyIdentityRequest{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyIdentityRequest) ProtoMessage() {}

func (x *ApplyIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyIdentityRequest.ProtoReflect.Descriptor instead.
func (*ApplyIdentityRequest) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{12}
}

func (x *ApplyIdentityRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *ApplyIdentityRequest) GetFallbackSecret() string {
	if x != nil {
		return x.FallbackSecret
	}
	return ""
}

func (x *ApplyIdentityRequest) GetKubernetesShare() []byte {
	if x != nil {
		return x.KubernetesShare
	}
	return nil
}

func (x *ApplyIdentityRequest) GetNodeCertificate() []byte {
	if x != nil {
		return x.NodeCertificate
	}
	return nil
}

func (x *ApplyIdentityRequest) GetNodeKey() []byte {
	if x != nil {
		return x.NodeKey
	}
	return nil
}

func (x *ApplyIdentityRequest) GetTrust() []byte {
	if x != nil {
		return x.Trust
	}
	return nil
}

type ApplyIdentityResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Storage changes that were applied.
	Changes []*StorageChange `protobuf:"bytes,1,rep,name=changes,proto3" json:"changes,omitempty"`
	// Units restarted because identity keys they read changed.
	RestartedUnits []string `protobuf:"bytes,2,rep,name=restarted_units,json=restartedUnits,proto3" json:"restarted_units,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApplyIdentityResponse) Reset() {
	*x = ApplyIdentityResponse{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyIdentityResponse) ProtoMessage() {}

func (x *ApplyIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyIdentityResponse.ProtoReflect.Descriptor instead.
func (*ApplyIdentityResponse) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{13}
}

func (x *ApplyIdentityResponse) GetChanges() []*StorageChange {
	if x != nil {
		return x.Changes
	}
	return nil
}

func (x *ApplyIdentityResponse) GetRestartedUnits() []string {
	if x != nil {
		return x.RestartedUnits
	}
	return nil
}

type StorageChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volume        string                 `protobuf:"bytes,1,opt,name=volume,proto3" json:"volume,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Destructive   bool                   `protobuf:"varint,3,opt,name=destructive,proto3" json:"destructive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageChange) Reset() {
	*x = StorageChange{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageChange) ProtoMessage() {}

func (x *StorageChange) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageChange.ProtoReflect.Descriptor instead.
func (*StorageChange) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{14}
}

func (x *StorageChange) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *StorageChange) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *StorageChange) GetDestructive() bool {
	if x != nil {
		return x.Destructive
	}
	return false
}

type ResetVolumeRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Volume string                 `protobuf:"bytes,1,opt,name=volume,proto3" json:"volume,omitempty"`
	// The node's identity as the manifest renders it (JSON); the volume is created as it defines.
	Identity       string `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	FallbackSecret string `protobuf:"bytes,3,opt,name=fallback_secret,json=fallbackSecret,proto3" json:"fallback_secret,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResetVolumeRequest) Reset() {
	*x = ResetVolumeRequest{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetVolumeRequest) ProtoMessage() {}

func (x *ResetVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetVolumeRequest.ProtoReflect.Descriptor instead.
func (*ResetVolumeRequest) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{15}
}

func (x *ResetVolumeRequest) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *ResetVolumeRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *ResetVolumeRequest) GetFallbackSecret() string {
	if x != nil {
		return x.FallbackSecret
	}
	return ""
}

type ResetVolumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetVolumeResponse) Reset() {
	*x = ResetVolumeResponse{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetVolumeResponse) ProtoMessage() {}

func (x *ResetVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetVolumeResponse.ProtoReflect.Descriptor instead.
func (*ResetVolumeResponse) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{16}
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{17}
}

type StatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SHA-256 of the identity document the node runs, in lower-case hex.
	IdentityVersion string          `protobuf:"bytes,1,opt,name=identity_version,json=identityVersion,proto3" json:"identity_version,omitempty"`
	Disks           []*DiskStatus   `protobuf:"bytes,2,rep,name=disks,proto3" json:"disks,omitempty"`
	Volumes         []*VolumeStatus `protobuf:"bytes,3,rep,name=volumes,proto3" json:"volumes,omitempty"`
	FailedUnits     []string        `protobuf:"bytes,4,rep,name=failed_units,json=failedUnits,proto3" json:"failed_units,omitempty"`
	// Absent on a node of a role without Kubernetes.
	Kubernetes *KubernetesStatus `protobuf:"bytes,5,opt,name=kubernetes,proto3" json:"kubernetes,omitempty"`
	// Every certificate the node holds or issues, with its expiry and what needs doing about it.
	Certificates []*CertificateStatus `protobuf:"bytes,6,rep,name=certificates,proto3" json:"certificates,omitempty"`
	// How the node keeps its clock.
	Time *TimeStatus `protobuf:"bytes,7,opt,name=time,proto3" json:"time,omitempty"`
	// What the node trusts and issues with, by fingerprint.
	Trust         []*TrustStatus `protobuf:"bytes,8,rep,name=trust,proto3" json:"trust,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{18}
}

func (x *StatusResponse) GetIdentityVersion() string {
	if x != nil {
		return x.IdentityVersion
	}
	return ""
}

func (x *StatusResponse) GetDisks() []*DiskStatus {
	if x != nil {
		return x.Disks
	}
	return nil
}

func (x *StatusResponse) GetVolumes() []*VolumeStatus {
	if x != nil {
		return x.Volumes
	}
	return nil
}

func (x *StatusResponse) GetFailedUnits() []string {
	if x != nil {
		return x.FailedUnits
	}
	return nil
}

func (x *StatusResponse) GetKubernetes() *KubernetesStatus {
	if x != nil {
		return x.Kubernetes
	}
	return nil
}

func (x *StatusResponse) GetCertificates() []*CertificateStatus {
	if x != nil {
		return x.Certificates
	}
	return nil
}

func (x *StatusResponse) GetTime() *TimeStatus {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *StatusResponse) GetTrust() []*TrustStatus {
	if x != nil {
		return x.Trust
	}
	return nil
}

type TrustStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// What is trusted: "OS CA" on every node; "Kubernetes CA" on nodes with Kubernetes; on
	// control-plane nodes also "front-proxy CA", "etcd CA", "service-account keys" and "encryption
	// keys".
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The SHA-256 fingerprints of what is trusted, in lower-case hex: of certificates and of public
	// keys in DER, and of encryption keys hashed apart from both. The one that issues or signs
	// comes first.
	Fingerprints []string `protobuf:"bytes,2,rep,name=fingerprints,proto3" json:"fingerprints,omitempty"`
	// The fingerprint of the value the node issues, signs or encrypts with; empty where it does
	// none of these.
	Issuing       string `protobuf:"bytes,3,opt,name=issuing,proto3" json:"issuing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrustStatus) Reset() {
	*x = TrustStatus{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrustStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrustStatus) ProtoMessage() {}

func (x *TrustStatus) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrustStatus.ProtoReflect.Descriptor instead.
func (*TrustStatus) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{19}
}

func (x *TrustStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TrustStatus) GetFingerprints() []string {
	if x != nil {
		return x.Fingerprints
	}
	return nil
}

func (x *TrustStatus) GetIssuing() string {
	if x != nil {
		return x.Issuing
	}
	return ""
}

type CertificateStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// What the certificate is: "node", "OS CA", "node CA", "Kubernetes CA", "front-proxy CA",
	// "etcd CA", "Kubernetes control plane" (the control plane's leaf certificates, by the one
	// that expires first), "kubelet client" or "kubelet serving"; "Kubernetes share" when the
	// node's share cannot be read, so the certificates it holds are unknown.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Unset when the expiry is unknown.
	NotAfter *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	// Why a renewal fails, such as "renewal failing: <reason>; expires <date>", or a warning, such
	// as "less than a third of its lifetime remains" or "node CA expires <date>; run chalkctl
	// node-ca rotate"; empty when there is nothing to do. <node> stands for the node's name.
	Problem string `protobuf:"bytes,3,opt,name=problem,proto3" json:"problem,omitempty"`
	// The SHA-256 fingerprint of the certificate, and of the certificate that issued it when the
	// node holds that one, in lower-case hex.
	Fingerprint   string `protobuf:"bytes,4,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	Issuer        string `protobuf:"bytes,5,opt,name=issuer,proto3" json:"issuer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertificateStatus) Reset() {
	*x = CertificateStatus{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateStatus) ProtoMessage() {}

func (x *CertificateStatus) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateStatus.ProtoReflect.Descriptor instead.
func (*CertificateStatus) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{20}
}

func (x *CertificateStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CertificateStatus) GetNotAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.NotAfter
	}
	return nil
}

func (x *CertificateStatus) GetProblem() string {
	if x != nil {
		return x.Problem
	}
	return ""
}

func (x *CertificateStatus) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *CertificateStatus) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

type TimeStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether chrony synchronises the clock with a server.
	Synchronised bool `protobuf:"varint,1,opt,name=synchronised,proto3" json:"synchronised,omitempty"`
	// The server the clock follows.
	Source string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	// How far the clock is from the server's time, in seconds; positive when it is ahead.
	OffsetSeconds float64 `protobuf:"fixed64,3,opt,name=offset_seconds,json=offsetSeconds,proto3" json:"offset_seconds,omitempty"`
	// Why chrony's state could not be read; empty when it was.
	Error         string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeStatus) Reset() {
	*x = TimeStatus{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeStatus) ProtoMessage() {}

func (x *TimeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeStatus.ProtoReflect.Descriptor instead.
func (*TimeStatus) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{21}
}

func (x *TimeStatus) GetSynchronised() bool {
	if x != nil {
		return x.Synchronised
	}
	return false
}

func (x *TimeStatus) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *TimeStatus) GetOffsetSeconds() float64 {
	if x != nil {
		return x.OffsetSeconds
	}
	return 0
}

func (x *TimeStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type KubernetesStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// controlplane or worker.
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// What the node waits for or is: "no share", "preparing" while its Kubernetes files are
	// prepared, or why their preparation failed, such as "preparation failed: no ipv4 node address
	// matches validSubnets 10.0.0.0/8 (the node has ...)"; then on a control-plane node "waiting
	// for bootstrap or for the cluster at <endpoint>", what joining that cluster does or waits for,
	// such as "joining the cluster at <endpoint>: etcd member <id> catches up" or a stale member
	// and how to remove it, "bootstrapped" or "etcd data missing: restore etcd or reinstall the
	// node"; "joined" on a worker, followed by ": the Node has no <family> pod range; ..." when the
	// control plane allocated it no pod range of one of the worker's families.
	State string `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	// The status of the Node's Ready condition (True, False or Unknown), or why it could not be
	// read.
	NodeReady string `protobuf:"bytes,3,opt,name=node_ready,json=nodeReady,proto3" json:"node_ready,omitempty"`
	// On a bootstrapped control-plane node of a cluster with VIPs: "holder" while the node holds
	// them, "standby" otherwise. Empty on other nodes.
	Vip string `protobuf:"bytes,4,opt,name=vip,proto3" json:"vip,omitempty"`
	// On a bootstrapped control-plane node: "current" once its API server and etcd serve the
	// certificates the node holds now and the API server answers ready, otherwise what is not so,
	// such as "the API server serves certificates the node replaced". Empty on other nodes.
	ControlPlane  string `protobuf:"bytes,5,opt,name=control_plane,json=controlPlane,proto3" json:"control_plane,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubernetesStatus) Reset() {
	*x = KubernetesStatus{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubernetesStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesStatus) ProtoMessage() {}

func (x *KubernetesStatus) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesStatus.ProtoReflect.Descriptor instead.
func (*KubernetesStatus) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{22}
}

func (x *KubernetesStatus) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *KubernetesStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *KubernetesStatus) GetNodeReady() string {
	if x != nil {
		return x.NodeReady
	}
	return ""
}

func (x *KubernetesStatus) GetVip() string {
	if x != nil {
		return x.Vip
	}
	return ""
}

func (x *KubernetesStatus) GetControlPlane() string {
	if x != nil {
		return x.ControlPlane
	}
	return ""
}

type DiskStatus struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Name   string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Device string                 `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	// Why the disk's volumes could not be created or opened at boot; empty when they were.
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskStatus) Reset() {
	*x = DiskStatus{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskStatus) ProtoMessage() {}

func (x *DiskStatus) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskStatus.ProtoReflect.Descriptor instead.
func (*DiskStatus) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{23}
}

func (x *DiskStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DiskStatus) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *DiskStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type VolumeStatus struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Name       string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Disk       string                 `protobuf:"bytes,2,opt,name=disk,proto3" json:"disk,omitempty"`
	MountPoint string                 `protobuf:"bytes,3,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
	// Whether the volume's partition exists.
	Present bool `protobuf:"varint,4,opt,name=present,proto3" json:"present,omitempty"`
	// Whether the volume is mounted at its mount point.
	Mounted       bool `protobuf:"varint,5,opt,name=mounted,proto3" json:"mounted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeStatus) Reset() {
	*x = VolumeStatus{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeStatus) ProtoMessage() {}

func (x *VolumeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeStatus.ProtoReflect.Descriptor instead.
func (*VolumeStatus) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{24}
}

func (x *VolumeStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VolumeStatus) GetDisk() string {
	if x != nil {
		return x.Disk
	}
	return ""
}

func (x *VolumeStatus) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

func (x *VolumeStatus) GetPresent() bool {
	if x != nil {
		return x.Present
	}
	return false
}

func (x *VolumeStatus) GetMounted() bool {
	if x != nil {
		return x.Mounted
	}
	return false
}

type LogsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unit whose journal to stream; empty streams the whole boot.
	Unit string `protobuf:"bytes,1,opt,name=unit,proto3" json:"unit,omitempty"`
	// Keep streaming new entries until the client cancels.
	Follow        bool `protobuf:"varint,2,opt,name=follow,proto3" json:"follow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsRequest) Reset() {
	*x = LogsRequest{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsRequest) ProtoMessage() {}

func (x *LogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsRequest.ProtoReflect.Descriptor instead.
func (*LogsRequest) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{25}
}

func (x *LogsRequest) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *LogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

type LogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line          string                 `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsResponse) Reset() {
	*x = LogsResponse{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsResponse) ProtoMessage() {}

func (x *LogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsResponse.ProtoReflect.Descriptor instead.
func (*LogsResponse) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{26}
}

func (x *LogsResponse) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

type RebootRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebootRequest) Reset() {
	*x = RebootRequest{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebootRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebootRequest) ProtoMessage() {}

func (x *RebootRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebootRequest.ProtoReflect.Descriptor instead.
func (*RebootRequest) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{27}
}

type RebootResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebootResponse) Reset() {
	*x = RebootResponse{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebootResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebootResponse) ProtoMessage() {}

func (x *RebootResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebootResponse.ProtoReflect.Descriptor instead.
func (*RebootResponse) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{28}
}

type BootstrapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapRequest) Reset() {
	*x = BootstrapRequest{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapRequest) ProtoMessage() {}

func (x *BootstrapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapRequest.ProtoReflect.Descriptor instead.
func (*BootstrapRequest) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{29}
}

type BootstrapResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Objects applied from the cluster's manifests.
	Applied       uint32 `protobuf:"varint,1,opt,name=applied,proto3" json:"applied,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapResponse) Reset() {
	*x = BootstrapResponse{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapResponse) ProtoMessage() {}

func (x *BootstrapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapResponse.ProtoReflect.Descriptor instead.
func (*BootstrapResponse) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{30}
}

func (x *BootstrapResponse) GetApplied() uint32 {
	if x != nil {
		return x.Applied
	}
	return 0
}

type EtcdMember struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// The node's name; empty while a member that was added has not started.
	Name     string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PeerUrls []string `protobuf:"bytes,3,rep,name=peer_urls,json=peerUrls,proto3" json:"peer_urls,omitempty"`
	Learner  bool     `protobuf:"varint,4,opt,name=learner,proto3" json:"learner,omitempty"`
	// Why the member did not answer; empty when it is healthy.
	Unhealthy     string `protobuf:"bytes,5,opt,name=unhealthy,proto3" json:"unhealthy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EtcdMember) Reset() {
	*x = EtcdMember{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EtcdMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EtcdMember) ProtoMessage() {}

func (x *EtcdMember) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EtcdMember.ProtoReflect.Descriptor instead.
func (*EtcdMember) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{31}
}

func (x *EtcdMember) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EtcdMember) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EtcdMember) GetPeerUrls() []string {
	if x != nil {
		return x.PeerUrls
	}
	return nil
}

func (x *EtcdMember) GetLearner() bool {
	if x != nil {
		return x.Learner
	}
	return false
}

func (x *EtcdMember) GetUnhealthy() string {
	if x != nil {
		return x.Unhealthy
	}
	return ""
}

type EtcdMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EtcdMembersRequest) Reset() {
	*x = EtcdMembersRequest{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EtcdMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EtcdMembersRequest) ProtoMessage() {}

func (x *EtcdMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EtcdMembersRequest.ProtoReflect.Descriptor instead.
func (*EtcdMembersRequest) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{32}
}

type EtcdMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*EtcdMember          `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EtcdMembersResponse) Reset() {
	*x = EtcdMembersResponse{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EtcdMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EtcdMembersResponse) ProtoMessage() {}

func (x *EtcdMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EtcdMembersResponse.ProtoReflect.Descriptor instead.
func (*EtcdMembersResponse) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{33}
}

func (x *EtcdMembersResponse) GetMembers() []*EtcdMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type EtcdRemoveMemberRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The member's name or its ID in hex.
	Member string `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	// Remove the member even when the voters left would have no healthy quorum.
	Force         bool `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EtcdRemoveMemberRequest) Reset() {
	*x = EtcdRemoveMemberRequest{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EtcdRemoveMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EtcdRemoveMemberRequest) ProtoMessage() {}

func (x *EtcdRemoveMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EtcdRemoveMemberRequest.ProtoReflect.Descriptor instead.
func (*EtcdRemoveMemberRequest) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{34}
}

func (x *EtcdRemoveMemberRequest) GetMember() string {
	if x != nil {
		return x.Member
	}
	return ""
}

func (x *EtcdRemoveMemberRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type EtcdRemoveMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Removed       *EtcdMember            `protobuf:"bytes,1,opt,name=removed,proto3" json:"removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EtcdRemoveMemberResponse) Reset() {
	*x = EtcdRemoveMemberResponse{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EtcdRemoveMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EtcdRemoveMemberResponse) ProtoMessage() {}

func (x *EtcdRemoveMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EtcdRemoveMemberResponse.ProtoReflect.Descriptor instead.
func (*EtcdRemoveMemberResponse) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{35}
}

func (x *EtcdRemoveMemberResponse) GetRemoved() *EtcdMember {
	if x != nil {
		return x.Removed
	}
	return nil
}

type EtcdLeaveRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Leave through the other members also when the node's own etcd member does not answer, as on
	// a node that lost its pinned address.
	Force         bool `protobuf:"varint,1,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EtcdLeaveRequest) Reset() {
	*x = EtcdLeaveRequest{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EtcdLeaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EtcdLeaveRequest) ProtoMessage() {}

func (x *EtcdLeaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EtcdLeaveRequest.ProtoReflect.Descriptor instead.
func (*EtcdLeaveRequest) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{36}
}

func (x *EtcdLeaveRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type EtcdLeaveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EtcdLeaveResponse) Reset() {
	*x = EtcdLeaveResponse{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EtcdLeaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EtcdLeaveResponse) ProtoMessage() {}

func (x *EtcdLeaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EtcdLeaveResponse.ProtoReflect.Descriptor instead.
func (*EtcdLeaveResponse) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{37}
}

type RenewNodeCertificateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PKCS #10 certificate request (DER) signed with the node's new key, which never leaves the
	// node. Only its key is used; the names come from the caller's certificate.
	CertificateRequest []byte `protobuf:"bytes,1,opt,name=certificate_request,json=certificateRequest,proto3" json:"certificate_request,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RenewNodeCertificateRequest) Reset() {
	*x = RenewNodeCertificateRequest{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewNodeCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewNodeCertificateRequest) ProtoMessage() {}

func (x *RenewNodeCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewNodeCertificateRequest.ProtoReflect.Descriptor instead.
func (*RenewNodeCertificateRequest) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{38}
}

func (x *RenewNodeCertificateRequest) GetCertificateRequest() []byte {
	if x != nil {
		return x.CertificateRequest
	}
	return nil
}

type RenewNodeCertificateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The new node certificate followed by the certificate of the node CA that issued it (PEM).
	CertificateChain []byte `protobuf:"bytes,1,opt,name=certificate_chain,json=certificateChain,proto3" json:"certificate_chain,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RenewNodeCertificateResponse) Reset() {
	*x = RenewNodeCertificateResponse{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewNodeCertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewNodeCertificateResponse) ProtoMessage() {}

func (x *RenewNodeCertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewNodeCertificateResponse.ProtoReflect.Descriptor instead.
func (*RenewNodeCertificateResponse) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{39}
}

func (x *RenewNodeCertificateResponse) GetCertificateChain() []byte {
	if x != nil {
		return x.CertificateChain
	}
	return nil
}

var File_chalkos_node_v1_node_proto protoreflect.FileDescriptor

const file_chalkos_node_v1_node_proto_rawDesc = "" +
	"\n" +
	"\x1achalkos/node/v1/node.proto\x12\x0fchalkos.node.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\r\n" +
	"\vInfoRequest\"\xb7\x02\n" +
	"\fInfoResponse\x12)\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x15.chalkos.node.v1.ModeR\x04mode\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x19\n" +
	"\bimage_id\x18\x03 \x01(\tR\aimageId\x12\x1c\n" +
	"\tinstaller\x18\x04 \x01(\bR\tinstaller\x12\x1b\n" +
	"\tboot_disk\x18\x05 \x01(\tR\bbootDisk\x12\x10\n" +
	"\x03tpm\x18\x06 \x01(\bR\x03tpm\x12<\n" +
	"\vsecure_boot\x18\a \x01(\x0e2\x1b.chalkos.node.v1.SecureBootR\n" +
	"secureBoot\x12 \n" +
	"\vfingerprint\x18\b \x01(\tR\vfingerprint\x12\x1a\n" +
	"\bhostname\x18\t \x01(\tR\bhostname\"\x0e\n" +
	"\fDisksRequest\"<\n" +
	"\rDisksResponse\x12+\n" +
	"\x05disks\x18\x01 \x03(\v2\x15.chalkos.node.v1.DiskR\x05disks\"\x80\x02\n" +
	"\x04Disk\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06device\x18\x02 \x01(\tR\x06device\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x04R\x04size\x12\x16\n" +
	"\x06serial\x18\x05 \x01(\tR\x06serial\x12\x10\n" +
	"\x03wwn\x18\x06 \x01(\tR\x03wwn\x12\x12\n" +
	"\x04type\x18\a \x01(\tR\x04type\x12\x12\n" +
	"\x04path\x18\b \x01(\tR\x04path\x12:\n" +
	"\n" +
	"partitions\x18\t \x03(\v2\x1a.chalkos.node.v1.PartitionR\n" +
	"partitions\x12\x14\n" +
	"\x05usage\x18\n" +
	" \x01(\tR\x05usage\"\xa7\x01\n" +
	"\tPartition\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x16\n" +
	"\x06number\x18\x02 \x01(\rR\x06number\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x14\n" +
	"\x05label\x18\x05 \x01(\tR\x05label\x12\x12\n" +
	"\x04uuid\x18\x06 \x01(\tR\x04uuid\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\"\x8a\x01\n" +
	"\x0eInstallRequest\x128\n" +
	"\x06header\x18\x01 \x01(\v2\x1e.chalkos.node.v1.InstallHeaderH\x00R\x06header\x123\n" +
	"\x05chunk\x18\x02 \x01(\v2\x1b.chalkos.node.v1.ImageChunkH\x00R\x05chunkB\t\n" +
	"\amessage\"\xee\x04\n" +
	"\rInstallHeader\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12)\n" +
	"\x10node_certificate\x18\x02 \x01(\fR\x0fnodeCertificate\x12\x19\n" +
	"\bnode_key\x18\x03 \x01(\fR\anodeKey\x12%\n" +
	"\x0eca_certificate\x18\x04 \x01(\fR\rcaCertificate\x12'\n" +
	"\x0ffallback_secret\x18\x05 \x01(\tR\x0efallbackSecret\x125\n" +
	"\bin_place\x18\x06 \x01(\v2\x18.chalkos.node.v1.InPlaceH\x00R\ainPlace\x124\n" +
	"\x04disk\x18\a \x01(\v2\x1e.chalkos.node.v1.DiskReferenceH\x00R\x04disk\x12\x1d\n" +
	"\n" +
	"image_size\x18\b \x01(\x04R\timageSize\x12!\n" +
	"\fimage_sha256\x18\t \x01(\fR\vimageSha256\x12\x1b\n" +
	"\twipe_disk\x18\n" +
	" \x01(\bR\bwipeDisk\x12d\n" +
	"\x12system_definitions\x18\v \x03(\v25.chalkos.node.v1.InstallHeader.SystemDefinitionsEntryR\x11systemDefinitions\x12)\n" +
	"\x10kubernetes_share\x18\f \x01(\fR\x0fkubernetesShare\x1aD\n" +
	"\x16SystemDefinitionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\b\n" +
	"\x06target\"\t\n" +
	"\aInPlace\"\x8b\x01\n" +
	"\rDiskReference\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x16\n" +
	"\x06serial\x18\x03 \x01(\tR\x06serial\x12\x10\n" +
	"\x03wwn\x18\x04 \x01(\tR\x03wwn\x12\x12\n" +
	"\x04size\x18\x05 \x01(\tR\x04size\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\" \n" +
	"\n" +
	"ImageChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x11\n" +
	"\x0fInstallResponse\"\xe2\x01\n" +
	"\x14ApplyIdentityRequest\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12'\n" +
	"\x0ffallback_secret\x18\x02 \x01(\tR\x0efallbackSecret\x12)\n" +
	"\x10kubernetes_share\x18\x03 \x01(\fR\x0fkubernetesShare\x12)\n" +
	"\x10node_certificate\x18\x04 \x01(\fR\x0fnodeCertificate\x12\x19\n" +
	"\bnode_key\x18\x05 \x01(\fR\anodeKey\x12\x14\n" +
	"\x05trust\x18\x06 \x01(\fR\x05trust\"z\n" +
	"\x15ApplyIdentityResponse\x128\n" +
	"\achanges\x18\x01 \x03(\v2\x1e.chalkos.node.v1.StorageChangeR\achanges\x12'\n" +
	"\x0frestarted_units\x18\x02 \x03(\tR\x0erestartedUnits\"a\n" +
	"\rStorageChange\x12\x16\n" +
	"\x06volume\x18\x01 \x01(\tR\x06volume\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12 \n" +
	"\vdestructive\x18\x03 \x01(\bR\vdestructive\"q\n" +
	"\x12ResetVolumeRequest\x12\x16\n" +
	"\x06volume\x18\x01 \x01(\tR\x06volume\x12\x1a\n" +
	"\bidentity\x18\x02 \x01(\tR\bidentity\x12'\n" +
	"\x0ffallback_secret\x18\x03 \x01(\tR\x0efallbackSecret\"\x15\n" +
	"\x13ResetVolumeResponse\"\x0f\n" +
	"\rStatusRequest\"\xba\x03\n" +
	"\x0eStatusResponse\x12)\n" +
	"\x10identity_version\x18\x01 \x01(\tR\x0fidentityVersion\x121\n" +
	"\x05disks\x18\x02 \x03(\v2\x1b.chalkos.node.v1.DiskStatusR\x05disks\x127\n" +
	"\avolumes\x18\x03 \x03(\v2\x1d.chalkos.node.v1.VolumeStatusR\avolumes\x12!\n" +
	"\ffailed_units\x18\x04 \x03(\tR\vfailedUnits\x12A\n" +
	"\n" +
	"kubernetes\x18\x05 \x01(\v2!.chalkos.node.v1.KubernetesStatusR\n" +
	"kubernetes\x12F\n" +
	"\fcertificates\x18\x06 \x03(\v2\".chalkos.node.v1.CertificateStatusR\fcertificates\x12/\n" +
	"\x04time\x18\a \x01(\v2\x1b.chalkos.node.v1.TimeStatusR\x04time\x122\n" +
	"\x05trust\x18\b \x03(\v2\x1c.chalkos.node.v1.TrustStatusR\x05trust\"_\n" +
	"\vTrustStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\"\n" +
	"\ffingerprints\x18\x02 \x03(\tR\ffingerprints\x12\x18\n" +
	"\aissuing\x18\x03 \x01(\tR\aissuing\"\xb4\x01\n" +
	"\x11CertificateStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x127\n" +
	"\tnot_after\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bnotAfter\x12\x18\n" +
	"\aproblem\x18\x03 \x01(\tR\aproblem\x12 \n" +
	"\vfingerprint\x18\x04 \x01(\tR\vfingerprint\x12\x16\n" +
	"\x06issuer\x18\x05 \x01(\tR\x06issuer\"\x85\x01\n" +
	"\n" +
	"TimeStatus\x12\"\n" +
	"\fsynchronised\x18\x01 \x01(\bR\fsynchronised\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12%\n" +
	"\x0eoffset_seconds\x18\x03 \x01(\x01R\roffsetSeconds\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x92\x01\n" +
	"\x10KubernetesStatus\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x1d\n" +
	"\n" +
	"node_ready\x18\x03 \x01(\tR\tnodeReady\x12\x10\n" +
	"\x03vip\x18\x04 \x01(\tR\x03vip\x12#\n" +
	"\rcontrol_plane\x18\x05 \x01(\tR\fcontrolPlane\"N\n" +
	"\n" +
	"DiskStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06device\x18\x02 \x01(\tR\x06device\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x8b\x01\n" +
	"\fVolumeStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04disk\x18\x02 \x01(\tR\x04disk\x12\x1f\n" +
	"\vmount_point\x18\x03 \x01(\tR\n" +
	"mountPoint\x12\x18\n" +
	"\apresent\x18\x04 \x01(\bR\apresent\x12\x18\n" +
	"\amounted\x18\x05 \x01(\bR\amounted\"9\n" +
	"\vLogsRequest\x12\x12\n" +
	"\x04unit\x18\x01 \x01(\tR\x04unit\x12\x16\n" +
	"\x06follow\x18\x02 \x01(\bR\x06follow\"\"\n" +
	"\fLogsResponse\x12\x12\n" +
	"\x04line\x18\x01 \x01(\tR\x04line\"\x0f\n" +
	"\rRebootRequest\"\x10\n" +
	"\x0eRebootResponse\"\x12\n" +
	"\x10BootstrapRequest\"-\n" +
	"\x11BootstrapResponse\x12\x18\n" +
	"\aapplied\x18\x01 \x01(\rR\aapplied\"\x85\x01\n" +
	"\n" +
	"EtcdMember\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tpeer_urls\x18\x03 \x03(\tR\bpeerUrls\x12\x18\n" +
	"\alearner\x18\x04 \x01(\bR\alearner\x12\x1c\n" +
	"\tunhealthy\x18\x05 \x01(\tR\tunhealthy\"\x14\n" +
	"\x12EtcdMembersRequest\"L\n" +
	"\x13EtcdMembersResponse\x125\n" +
	"\amembers\x18\x01 \x03(\v2\x1b.chalkos.node.v1.EtcdMemberR\amembers\"G\n" +
	"\x17EtcdRemoveMemberRequest\x12\x16\n" +
	"\x06member\x18\x01 \x01(\tR\x06member\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"Q\n" +
	"\x18EtcdRemoveMemberResponse\x125\n" +
	"\aremoved\x18\x01 \x01(\v2\x1b.chalkos.node.v1.EtcdMemberR\aremoved\"(\n" +
	"\x10EtcdLeaveRequest\x12\x14\n" +
	"\x05force\x18\x01 \x01(\bR\x05force\"\x13\n" +
	"\x11EtcdLeaveResponse\"N\n" +
	"\x1bRenewNodeCertificateRequest\x12/\n" +
	"\x13certificate_request\x18\x01 \x01(\fR\x12certificateRequest\"K\n" +
	"\x1cRenewNodeCertificateResponse\x12+\n" +
	"\x11certificate_chain\x18\x01 \x01(\fR\x10certificateChain*C\n" +
	"\x04Mode\x12\x14\n" +
	"\x10MODE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10MODE_MAINTENANCE\x10\x01\x12\x0f\n" +
	"\vMODE_NORMAL\x10\x02*x\n" +
	"\n" +
	"SecureBoot\x12\x1b\n" +
	"\x17SECURE_BOOT_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14SECURE_BOOT_DISABLED\x10\x01\x12\x17\n" +
	"\x13SECURE_BOOT_ENABLED\x10\x02\x12\x1a\n" +
	"\x16SECURE_BOOT_SETUP_MODE\x10\x032\xe1\b\n" +
	"\vNodeService\x12C\n" +
	"\x04Info\x12\x1c.chalkos.node.v1.InfoRequest\x1a\x1d.chalkos.node.v1.InfoResponse\x12F\n" +
	"\x05Disks\x12\x1d.chalkos.node.v1.DisksRequest\x1a\x1e.chalkos.node.v1.DisksResponse\x12N\n" +
	"\aInstall\x12\x1f.chalkos.node.v1.InstallRequest\x1a .chalkos.node.v1.InstallResponse(\x01\x12^\n" +
	"\rApplyIdentity\x12%.chalkos.node.v1.ApplyIdentityRequest\x1a&.chalkos.node.v1.ApplyIdentityResponse\x12X\n" +
	"\vResetVolume\x12#.chalkos.node.v1.ResetVolumeRequest\x1a$.chalkos.node.v1.ResetVolumeResponse\x12I\n" +
	"\x06Status\x12\x1e.chalkos.node.v1.StatusRequest\x1a\x1f.chalkos.node.v1.StatusResponse\x12E\n" +
	"\x04Logs\x12\x1c.chalkos.node.v1.LogsRequest\x1a\x1d.chalkos.node.v1.LogsResponse0\x01\x12I\n" +
	"\x06Reboot\x12\x1e.chalkos.node.v1.RebootRequest\x1a\x1f.chalkos.node.v1.RebootResponse\x12R\n" +
	"\tBootstrap\x12!.chalkos.node.v1.BootstrapRequest\x1a\".chalkos.node.v1.BootstrapResponse\x12X\n" +
	"\vEtcdMembers\x12#.chalkos.node.v1.EtcdMembersRequest\x1a$.chalkos.node.v1.EtcdMembersResponse\x12g\n" +
	"\x10EtcdRemoveMember\x12(.chalkos.node.v1.EtcdRemoveMemberRequest\x1a).chalkos.node.v1.EtcdRemoveMemberResponse\x12R\n" +
	"\tEtcdLeave\x12!.chalkos.node.v1.EtcdLeaveRequest\x1a\".chalkos.node.v1.EtcdLeaveResponse\x12s\n" +
	"\x14RenewNodeCertificate\x12,.chalkos.node.v1.RenewNodeCertificateRequest\x1a-.chalkos.node.v1.RenewNodeCertificateResponseB2Z0github.com/trevex/chalkos/pkg/api/node/v1;nodev1b\x06proto3"

var (
	file_chalkos_node_v1_node_proto_rawDescOnce sync.Once
	file_chalkos_node_v1_node_proto_rawDescData []byte
)

func file_chalkos_node_v1_node_proto_rawDescGZIP() []byte {
	file_chalkos_node_v1_node_proto_rawDescOnce.Do(func() {
		file_chalkos_node_v1_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chalkos_node_v1_node_proto_rawDesc), len(file_chalkos_node_v1_node_proto_rawDesc)))
	})
	return file_chalkos_node_v1_node_proto_rawDescData
}

var file_chalkos_node_v1_node_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_chalkos_node_v1_node_proto_msgTypes = make([]protoimpl.MessageInfo, 41)
var file_chalkos_node_v1_node_proto_goTypes = []any{
	(Mode)(0),                            // 0: chalkos.node.v1.Mode
	(SecureBoot)(0),                      // 1: chalkos.node.v1.SecureBoot
	(*InfoRequest)(nil),                  // 2: chalkos.node.v1.InfoRequest
	(*InfoResponse)(nil),                 // 3: chalkos.node.v1.InfoResponse
	(*DisksRequest)(nil),                 // 4: chalkos.node.v1.DisksRequest
	(*DisksResponse)(nil),                // 5: chalkos.node.v1.DisksResponse
	(*Disk)(nil),                         // 6: chalkos.node.v1.Disk
	(*Partition)(nil),                    // 7: chalkos.node.v1.Partition
	(*InstallRequest)(nil),               // 8: chalkos.node.v1.InstallRequest
	(*InstallHeader)(nil),                // 9: chalkos.node.v1.InstallHeader
	(*InPlace)(nil),                      // 10: chalkos.node.v1.InPlace
	(*DiskReference)(nil),                // 11: chalkos.node.v1.DiskReference
	(*ImageChunk)(nil),                   // 12: chalkos.node.v1.ImageChunk
	(*InstallResponse)(nil),              // 13: chalkos.node.v1.InstallResponse
	(*ApplyIdentityRequest)(nil),         // 14: chalkos.node.v1.ApplyIdentityRequest
	(*ApplyIdentityResponse)(nil),        // 15: chalkos.node.v1.ApplyIdentityResponse
	(*StorageChange)(nil),                // 16: chalkos.node.v1.StorageChange
	(*ResetVolumeRequest)(nil),           // 17: chalkos.node.v1.ResetVolumeRequest
	(*ResetVolumeResponse)(nil),          // 18: chalkos.node.v1.ResetVolumeResponse
	(*StatusRequest)(nil),                // 19: chalkos.node.v1.StatusRequest
	(*StatusResponse)(nil),               // 20: chalkos.node.v1.StatusResponse
	(*TrustStatus)(nil),                  // 21: chalkos.node.v1.TrustStatus
	(*CertificateStatus)(nil),            // 22: chalkos.node.v1.CertificateStatus
	(*TimeStatus)(nil),                   // 23: chalkos.node.v1.TimeStatus
	(*KubernetesStatus)(nil),             // 24: chalkos.node.v1.KubernetesStatus
	(*DiskStatus)(nil),                   // 25: chalkos.node.v1.DiskStatus
	(*VolumeStatus)(nil),                 // 26: chalkos.node.v1.VolumeStatus
	(*LogsRequest)(nil),                  // 27: chalkos.node.v1.LogsRequest
	(*LogsResponse)(nil),                 // 28: chalkos.node.v1.LogsResponse
	(*RebootRequest)(nil),                // 29: chalkos.node.v1.RebootRequest
	(*RebootResponse)(nil),               // 30: chalkos.node.v1.RebootResponse
	(*BootstrapRequest)(nil),             // 31: chalkos.node.v1.BootstrapRequest
	(*BootstrapResponse)(nil),            // 32: chalkos.node.v1.BootstrapResponse
	(*EtcdMember)(nil),                   // 33: chalkos.node.v1.EtcdMember
	(*EtcdMembersRequest)(nil),           // 34: chalkos.node.v1.EtcdMembersRequest
	(*EtcdMembersResponse)(nil),          // 35: chalkos.node.v1.EtcdMembersResponse
	(*EtcdRemoveMemberRequest)(nil),      // 36: chalkos.node.v1.EtcdRemoveMemberRequest
	(*EtcdRemoveMemberResponse)(nil),     // 37: chalkos.node.v1.EtcdRemoveMemberResponse
	(*EtcdLeaveRequest)(nil),             // 38: chalkos.node.v1.EtcdLeaveRequest
	(*EtcdLeaveResponse)(nil),            // 39: chalkos.node.v1.EtcdLeaveResponse
	(*RenewNodeCertificateRequest)(nil),  // 40: chalkos.node.v1.RenewNodeCertificateRequest
	(*RenewNodeCertificateResponse)(nil), // 41: chalkos.node.v1.RenewNodeCertificateResponse
	nil,                                  // 42: chalkos.node.v1.InstallHeader.SystemDefinitionsEntry
	(*timestamppb.Timestamp)(nil),        // 43: google.protobuf.Timestamp
}
var file_chalkos_node_v1_node_proto_depIdxs = []int32{
	0,  // 0: chalkos.node.v1.InfoResponse.mode:type_name -> chalkos.node.v1.Mode
	1,  // 1: chalkos.node.v1.InfoResponse.secure_boot:type_name -> chalkos.node.v1.SecureBoot
	6,  // 2: chalkos.node.v1.DisksResponse.disks:type_name -> chalkos.node.v1.Disk
	7,  // 3: chalkos.node.v1.Disk.partitions:type_name -> chalkos.node.v1.Partition
	9,  // 4: chalkos.node.v1.InstallRequest.header:type_name -> chalkos.node.v1.InstallHeader
	12, // 5: chalkos.node.v1.InstallRequest.chunk:type_name -> chalkos.node.v1.ImageChunk
	10, // 6: chalkos.node.v1.InstallHeader.in_place:type_name -> chalkos.node.v1.InPlace
	11, // 7: chalkos.node.v1.InstallHeader.disk:type_name -> chalkos.node.v1.DiskReference
	42, // 8: chalkos.node.v1.InstallHeader.system_definitions:type_name -> chalkos.node.v1.InstallHeader.SystemDefinitionsEntry
	16, // 9: chalkos.node.v1.ApplyIdentityResponse.changes:type_name -> chalkos.node.v1.StorageChange
	25, // 10: chalkos.node.v1.StatusResponse.disks:type_name -> chalkos.node.v1.DiskStatus
	26, // 11: chalkos.node.v1.StatusResponse.volumes:type_name -> chalkos.node.v1.VolumeStatus
	24, // 12: chalkos.node.v1.StatusResponse.kubernetes:type_name -> chalkos.node.v1.KubernetesStatus
	22, // 13: chalkos.node.v1.StatusResponse.certificates:type_name -> chalkos.node.v1.CertificateStatus
	23, // 14: chalkos.node.v1.StatusResponse.time:type_name -> chalkos.node.v1.TimeStatus
	21, // 15: chalkos.node.v1.StatusResponse.trust:type_name -> chalkos.node.v1.TrustStatus
	43, // 16: chalkos.node.v1.CertificateStatus.not_after:type_name -> google.protobuf.Timestamp
	33, // 17: chalkos.node.v1.EtcdMembersResponse.members:type_name -> chalkos.node.v1.EtcdMember
	33, // 18: chalkos.node.v1.EtcdRemoveMemberResponse.removed:type_name -> chalkos.node.v1.EtcdMember
	2,  // 19: chalkos.node.v1.NodeService.Info:input_type -> chalkos.node.v1.InfoRequest
	4,  // 20: chalkos.node.v1.NodeService.Disks:input_type -> chalkos.node.v1.DisksRequest
	8,  // 21: chalkos.node.v1.NodeService.Install:input_type -> chalkos.node.v1.InstallRequest
	14, // 22: chalkos.node.v1.NodeService.ApplyIdentity:input_type -> chalkos.node.v1.ApplyIdentityRequest
	17, // 23: chalkos.node.v1.NodeService.ResetVolume:input_type -> chalkos.node.v1.ResetVolumeRequest
	19, // 24: chalkos.node.v1.NodeService.Status:input_type -> chalkos.node.v1.StatusRequest
	27, // 25: chalkos.node.v1.NodeService.Logs:input_type -> chalkos.node.v1.LogsRequest
	29, // 26: chalkos.node.v1.NodeService.Reboot:input_type -> chalkos.node.v1.RebootRequest
	31, // 27: chalkos.node.v1.NodeService.Bootstrap:input_type -> chalkos.node.v1.BootstrapRequest
	34, // 28: chalkos.node.v1.NodeService.EtcdMembers:input_type -> chalkos.node.v1.EtcdMembersRequest
	36, // 29: chalkos.node.v1.NodeService.EtcdRemoveMember:input_type -> chalkos.node.v1.EtcdRemoveMemberRequest
	38, // 30: chalkos.node.v1.NodeService.EtcdLeave:input_type -> chalkos.node.v1.EtcdLeaveRequest
	40, // 31: chalkos.node.v1.NodeService.RenewNodeCertificate:input_type -> chalkos.node.v1.RenewNodeCertificateRequest
	3,  // 32: chalkos.node.v1.NodeService.Info:output_type -> chalkos.node.v1.InfoResponse
	5,  // 33: chalkos.node.v1.NodeService.Disks:output_type -> chalkos.node.v1.DisksResponse
	13, // 34: chalkos.node.v1.NodeService.Install:output_type -> chalkos.node.v1.InstallResponse
	15, // 35: chalkos.node.v1.NodeService.ApplyIdentity:output_type -> chalkos.node.v1.ApplyIdentityResponse
	18, // 36: chalkos.node.v1.NodeService.ResetVolume:output_type -> chalkos.node.v1.ResetVolumeResponse
	20, // 37: chalkos.node.v1.NodeService.Status:output_type -> chalkos.node.v1.StatusResponse
	28, // 38: chalkos.node.v1.NodeService.Logs:output_type -> chalkos.node.v1.LogsResponse
	30, // 39: chalkos.node.v1.NodeService.Reboot:output_type -> chalkos.node.v1.RebootResponse
	32, // 40: chalkos.node.v1.NodeService.Bootstrap:output_type -> chalkos.node.v1.BootstrapResponse
	35, // 41: chalkos.node.v1.NodeService.EtcdMembers:output_type -> chalkos.node.v1.EtcdMembersResponse
	37, // 42: chalkos.node.v1.NodeService.EtcdRemoveMember:output_type -> chalkos.node.v1.EtcdRemoveMemberResponse
	39, // 43: chalkos.node.v1.NodeService.EtcdLeave:output_type -> chalkos.node.v1.EtcdLeaveResponse
	41, // 44: chalkos.node.v1.NodeService.RenewNodeCertificate:output_type -> chalkos.node.v1.RenewNodeCertificateResponse
	32, // [32:45] is the sub-list for method output_type
	19, // [19:32] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_chalkos_node_v1_node_proto_init() }
func file_chalkos_node_v1_node_proto_init() {
	if File_chalkos_node_v1_node_proto != nil {
		return
	}
	file_chalkos_node_v1_node_proto_msgTypes[6].OneofWrappers = []any{
		(*InstallRequest_Header)(nil),
		(*InstallRequest_Chunk)(nil),
	}
	file_chalkos_node_v1_node_proto_msgTypes[7].OneofWrappers = []any{
		(*InstallHeader_InPlace)(nil),
		(*InstallHeader_Disk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chalkos_node_v1_node_proto_rawDesc), len(file_chalkos_node_v1_node_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   41,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chalkos_node_v1_node_proto_goTypes,
		DependencyIndexes: file_chalkos_node_v1_node_proto_depIdxs,
		EnumInfos:         file_chalkos_node_v1_node_proto_enumTypes,
		MessageInfos:      file_chalkos_node_v1_node_proto_msgTypes,
	}.Build()
	File_chalkos_node_v1_node_proto = out.File
	file_chalkos_node_v1_node_proto_goTypes = nil
	file_chalkos_node_v1_node_proto_depIdxs = nil
}
