// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: chalkos/node/v1/node.proto

// The API of chalkd, the agent on every chalkos node and on the installer. chalkd serves it on
// TCP port 50000 over TLS; chalkctl is its client.

package nodev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Mode int32

const (
	Mode_MODE_UNSPECIFIED Mode = 0
	// The node is not installed: chalkd serves a self-signed certificate.
	Mode_MODE_MAINTENANCE Mode = 1
	// The node is installed: chalkd serves its node certificate and requires client certificates.
	Mode_MODE_NORMAL Mode = 2
)

// Enum value maps for Mode.
var (
	Mode_name = map[int32]string{
		0: "MODE_UNSPECIFIED",
		1: "MODE_MAINTENANCE",
		2: "MODE_NORMAL",
	}
	Mode_value = map[string]int32{
		"MODE_UNSPECIFIED": 0,
		"MODE_MAINTENANCE": 1,
		"MODE_NORMAL":      2,
	}
)

func (x Mode) Enum() *Mode {
	p := new(Mode)
	*p = x
	return p
}

func (x Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_chalkos_node_v1_node_proto_enumTypes[0].Descriptor()
}

func (Mode) Type() protoreflect.EnumType {
	return &file_chalkos_node_v1_node_proto_enumTypes[0]
}

func (x Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Mode.Descriptor instead.
func (Mode) EnumDescriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{0}
}

type SecureBoot int32

const (
	SecureBoot_SECURE_BOOT_UNSPECIFIED SecureBoot = 0
	SecureBoot_SECURE_BOOT_DISABLED    SecureBoot = 1
	SecureBoot_SECURE_BOOT_ENABLED     SecureBoot = 2
	// The firmware accepts new Secure Boot keys without authentication.
	SecureBoot_SECURE_BOOT_SETUP_MODE SecureBoot = 3
)

// Enum value maps for SecureBoot.
var (
	SecureBoot_name = map[int32]string{
		0: "SECURE_BOOT_UNSPECIFIED",
		1: "SECURE_BOOT_DISABLED",
		2: "SECURE_BOOT_ENABLED",
		3: "SECURE_BOOT_SETUP_MODE",
	}
	SecureBoot_value = map[string]int32{
		"SECURE_BOOT_UNSPECIFIED": 0,
		"SECURE_BOOT_DISABLED":    1,
		"SECURE_BOOT_ENABLED":     2,
		"SECURE_BOOT_SETUP_MODE":  3,
	}
)

func (x SecureBoot) Enum() *SecureBoot {
	p := new(SecureBoot)
	*p = x
	return p
}

func (x SecureBoot) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecureBoot) Descriptor() protoreflect.EnumDescriptor {
	return file_chalkos_node_v1_node_proto_enumTypes[1].Descriptor()
}

func (SecureBoot) Type() protoreflect.EnumType {
	return &file_chalkos_node_v1_node_proto_enumTypes[1]
}

func (x SecureBoot) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SecureBoot.Descriptor instead.
func (SecureBoot) EnumDescriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{1}
}

type InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{0}
}

type InfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Mode  Mode                   `protobuf:"varint,1,opt,name=mode,proto3,enum=chalkos.node.v1.Mode" json:"mode,omitempty"`
	// chalkos version of the running image.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Image ID of the running image, such as "chalkos".
	ImageId string `protobuf:"bytes,3,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	// Whether the node runs the installer, which writes a role image to another disk.
	Installer bool `protobuf:"varint,4,opt,name=installer,proto3" json:"installer,omitempty"`
	// Device of the disk the node booted from; empty on the installer booted from a CD.
	BootDisk   string     `protobuf:"bytes,5,opt,name=boot_disk,json=bootDisk,proto3" json:"boot_disk,omitempty"`
	Tpm        bool       `protobuf:"varint,6,opt,name=tpm,proto3" json:"tpm,omitempty"`
	SecureBoot SecureBoot `protobuf:"varint,7,opt,name=secure_boot,json=secureBoot,proto3,enum=chalkos.node.v1.SecureBoot" json:"secure_boot,omitempty"`
	// SHA-256 of the certificate chalkd serves, in lower-case hex.
	Fingerprint   string `protobuf:"bytes,8,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	Hostname      string `protobuf:"bytes,9,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{1}
}

func (x *InfoResponse) GetMode() Mode {
	if x != nil {
		return x.Mode
	}
	return Mode_MODE_UNSPECIFIED
}

func (x *InfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InfoResponse) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *InfoResponse) GetInstaller() bool {
	if x != nil {
		return x.Installer
	}
	return false
}

func (x *InfoResponse) GetBootDisk() string {
	if x != nil {
		return x.BootDisk
	}
	return ""
}

func (x *InfoResponse) GetTpm() bool {
	if x != nil {
		return x.Tpm
	}
	return false
}

func (x *InfoResponse) GetSecureBoot() SecureBoot {
	if x != nil {
		return x.SecureBoot
	}
	return SecureBoot_SECURE_BOOT_UNSPECIFIED
}

func (x *InfoResponse) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *InfoResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type DisksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisksRequest) Reset() {
	*x = DisksRequest{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisksRequest) ProtoMessage() {}

func (x *DisksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisksRequest.ProtoReflect.Descriptor instead.
func (*DisksRequest) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{2}
}

type DisksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Disks         []*Disk                `protobuf:"bytes,1,rep,name=disks,proto3" json:"disks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisksResponse) Reset() {
	*x = DisksResponse{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisksResponse) ProtoMessage() {}

func (x *DisksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisksResponse.ProtoReflect.Descriptor instead.
func (*DisksResponse) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{3}
}

func (x *DisksResponse) GetDisks() []*Disk {
	if x != nil {
		return x.Disks
	}
	return nil
}

type Disk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Kernel name, such as nvme0n1.
	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Device string `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	Model  string `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Size   uint64 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Serial string `protobuf:"bytes,5,opt,name=serial,proto3" json:"serial,omitempty"`
	Wwn    string `protobuf:"bytes,6,opt,name=wwn,proto3" json:"wwn,omitempty"`
	// nvme, ssd or hdd.
	Type string `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	// udev's ID_PATH.
	Path       string       `protobuf:"bytes,8,opt,name=path,proto3" json:"path,omitempty"`
	Partitions []*Partition `protobuf:"bytes,9,rep,name=partitions,proto3" json:"partitions,omitempty"`
	// How chalkos uses the disk: "boot" for the boot disk, "disk <name>" for a pinned disk of the
	// node's storage, empty when chalkos does not use it.
	Usage         string `protobuf:"bytes,10,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Disk) Reset() {
	*x = Disk{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Disk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disk) ProtoMessage() {}

func (x *Disk) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disk.ProtoReflect.Descriptor instead.
func (*Disk) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{4}
}

func (x *Disk) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Disk) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *Disk) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Disk) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Disk) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *Disk) GetWwn() string {
	if x != nil {
		return x.Wwn
	}
	return ""
}

func (x *Disk) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Disk) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Disk) GetPartitions() []*Partition {
	if x != nil {
		return x.Partitions
	}
	return nil
}

func (x *Disk) GetUsage() string {
	if x != nil {
		return x.Usage
	}
	return ""
}

type Partition struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Device string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	Number uint32                 `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	Size   uint64                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	// GPT partition type UUID.
	Type  string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Label string `protobuf:"bytes,5,opt,name=label,proto3" json:"label,omitempty"`
	Uuid  string `protobuf:"bytes,6,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// File system or other content blkid found, such as ext4 or crypto_LUKS.
	Content       string `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Partition) Reset() {
	*x = Partition{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Partition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Partition) ProtoMessage() {}

func (x *Partition) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Partition.ProtoReflect.Descriptor instead.
func (*Partition) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{5}
}

func (x *Partition) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *Partition) GetNumber() uint32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Partition) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Partition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Partition) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Partition) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Partition) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type InstallRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*InstallRequest_Header
	//	*InstallRequest_Chunk
	Message       isInstallRequest_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallRequest) Reset() {
	*x = InstallRequest{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallRequest) ProtoMessage() {}

func (x *InstallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallRequest.ProtoReflect.Descriptor instead.
func (*InstallRequest) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{6}
}

func (x *InstallRequest) GetMessage() isInstallRequest_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *InstallRequest) GetHeader() *InstallHeader {
	if x != nil {
		if x, ok := x.Message.(*InstallRequest_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *InstallRequest) GetChunk() *ImageChunk {
	if x != nil {
		if x, ok := x.Message.(*InstallRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isInstallRequest_Message interface {
	isInstallRequest_Message()
}

type InstallRequest_Header struct {
	Header *InstallHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type InstallRequest_Chunk struct {
	Chunk *ImageChunk `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*InstallRequest_Header) isInstallRequest_Message() {}

func (*InstallRequest_Chunk) isInstallRequest_Message() {}

type InstallHeader struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The node's identity as the manifest renders it (JSON), including its storage section.
	Identity string `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	// PEM certificate and key chalkd serves once the node is installed.
	NodeCertificate []byte `protobuf:"bytes,2,opt,name=node_certificate,json=nodeCertificate,proto3" json:"node_certificate,omitempty"`
	NodeKey         []byte `protobuf:"bytes,3,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
	// PEM certificate of the OS CA, which issues client certificates.
	CaCertificate []byte `protobuf:"bytes,4,opt,name=ca_certificate,json=caCertificate,proto3" json:"ca_certificate,omitempty"`
	// Recovery key or password enrolled as the second keyslot of every encrypted volume; empty
	// when the node's fallback is none.
	FallbackSecret string `protobuf:"bytes,5,opt,name=fallback_secret,json=fallbackSecret,proto3" json:"fallback_secret,omitempty"`
	// Types that are valid to be assigned to Target:
	//
	//	*InstallHeader_InPlace
	//	*InstallHeader_Disk
	Target isInstallHeader_Target `protobuf_oneof:"target"`
	// Size and SHA-256 of the streamed image; installer only.
	ImageSize   uint64 `protobuf:"varint,8,opt,name=image_size,json=imageSize,proto3" json:"image_size,omitempty"`
	ImageSha256 []byte `protobuf:"bytes,9,opt,name=image_sha256,json=imageSha256,proto3" json:"image_sha256,omitempty"`
	// Let the installer overwrite a target disk that carries data other than chalkos partitions.
	WipeDisk bool `protobuf:"varint,10,opt,name=wipe_disk,json=wipeDisk,proto3" json:"wipe_disk,omitempty"`
	// The role image's repart definitions of the system region (slot B, STATE) by file name;
	// installer only. Each role chooses its partition sizes, so the installer's own may not fit.
	SystemDefinitions map[string]string `protobuf:"bytes,11,rep,name=system_definitions,json=systemDefinitions,proto3" json:"system_definitions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InstallHeader) Reset() {
	*x = InstallHeader{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallHeader) ProtoMessage() {}

func (x *InstallHeader) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallHeader.ProtoReflect.Descriptor instead.
func (*InstallHeader) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{7}
}

func (x *InstallHeader) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *InstallHeader) GetNodeCertificate() []byte {
	if x != nil {
		return x.NodeCertificate
	}
	return nil
}

func (x *InstallHeader) GetNodeKey() []byte {
	if x != nil {
		return x.NodeKey
	}
	return nil
}

func (x *InstallHeader) GetCaCertificate() []byte {
	if x != nil {
		return x.CaCertificate
	}
	return nil
}

func (x *InstallHeader) GetFallbackSecret() string {
	if x != nil {
		return x.FallbackSecret
	}
	return ""
}

func (x *InstallHeader) GetTarget() isInstallHeader_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *InstallHeader) GetInPlace() *InPlace {
	if x != nil {
		if x, ok := x.Target.(*InstallHeader_InPlace); ok {
			return x.InPlace
		}
	}
	return nil
}

func (x *InstallHeader) GetDisk() *DiskReference {
	if x != nil {
		if x, ok := x.Target.(*InstallHeader_Disk); ok {
			return x.Disk
		}
	}
	return nil
}

func (x *InstallHeader) GetImageSize() uint64 {
	if x != nil {
		return x.ImageSize
	}
	return 0
}

func (x *InstallHeader) GetImageSha256() []byte {
	if x != nil {
		return x.ImageSha256
	}
	return nil
}

func (x *InstallHeader) GetWipeDisk() bool {
	if x != nil {
		return x.WipeDisk
	}
	return false
}

func (x *InstallHeader) GetSystemDefinitions() map[string]string {
	if x != nil {
		return x.SystemDefinitions
	}
	return nil
}

type isInstallHeader_Target interface {
	isInstallHeader_Target()
}

type InstallHeader_InPlace struct {
	// The role image already runs from the boot disk.
	InPlace *InPlace `protobuf:"bytes,6,opt,name=in_place,json=inPlace,proto3,oneof"`
}

type InstallHeader_Disk struct {
	// The installer writes the streamed image to this disk.
	Disk *DiskReference `protobuf:"bytes,7,opt,name=disk,proto3,oneof"`
}

func (*InstallHeader_InPlace) isInstallHeader_Target() {}

func (*InstallHeader_Disk) isInstallHeader_Target() {}

type InPlace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InPlace) Reset() {
	*x = InPlace{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InPlace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InPlace) ProtoMessage() {}

func (x *InPlace) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InPlace.ProtoReflect.Descriptor instead.
func (*InPlace) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{8}
}

// A disk by /dev path, or by a selector whose set fields must all match.
type DiskReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Serial        string                 `protobuf:"bytes,3,opt,name=serial,proto3" json:"serial,omitempty"`
	Wwn           string                 `protobuf:"bytes,4,opt,name=wwn,proto3" json:"wwn,omitempty"`
	Size          string                 `protobuf:"bytes,5,opt,name=size,proto3" json:"size,omitempty"`
	Type          string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskReference) Reset() {
	*x = DiskReference{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskReference) ProtoMessage() {}

func (x *DiskReference) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskReference.ProtoReflect.Descriptor instead.
func (*DiskReference) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{9}
}

func (x *DiskReference) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DiskReference) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *DiskReference) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *DiskReference) GetWwn() string {
	if x != nil {
		return x.Wwn
	}
	return ""
}

func (x *DiskReference) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *DiskReference) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ImageChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageChunk) Reset() {
	*x = ImageChunk{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageChunk) ProtoMessage() {}

func (x *ImageChunk) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageChunk.ProtoReflect.Descriptor instead.
func (*ImageChunk) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{10}
}

func (x *ImageChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type InstallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallResponse) Reset() {
	*x = InstallResponse{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallResponse) ProtoMessage() {}

func (x *InstallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallResponse.ProtoReflect.Descriptor instead.
func (*InstallResponse) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{11}
}

type ApplyIdentityRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The node's identity as the manifest renders it (JSON).
	Identity string `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	// Enrolled on encrypted volumes the identity adds; required when it adds one and the node's
	// fallback is not none.
	FallbackSecret string `protobuf:"bytes,2,opt,name=fallback_secret,json=fallbackSecret,proto3" json:"fallback_secret,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApplyIdentityRequest) Reset() {
	*x = ApplyIdentityRequest{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyIdentityRequest) ProtoMessage() {}

func (x *ApplyIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyIdentityRequest.ProtoReflect.Descriptor instead.
func (*ApplyIdentityRequest) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{12}
}

func (x *ApplyIdentityRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *ApplyIdentityRequest) GetFallbackSecret() string {
	if x != nil {
		return x.FallbackSecret
	}
	return ""
}

type ApplyIdentityResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Storage changes that were applied.
	Changes []*StorageChange `protobuf:"bytes,1,rep,name=changes,proto3" json:"changes,omitempty"`
	// Units restarted because identity keys they read changed.
	RestartedUnits []string `protobuf:"bytes,2,rep,name=restarted_units,json=restartedUnits,proto3" json:"restarted_units,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApplyIdentityResponse) Reset() {
	*x = ApplyIdentityResponse{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyIdentityResponse) ProtoMessage() {}

func (x *ApplyIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyIdentityResponse.ProtoReflect.Descriptor instead.
func (*ApplyIdentityResponse) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{13}
}

func (x *ApplyIdentityResponse) GetChanges() []*StorageChange {
	if x != nil {
		return x.Changes
	}
	return nil
}

func (x *ApplyIdentityResponse) GetRestartedUnits() []string {
	if x != nil {
		return x.RestartedUnits
	}
	return nil
}

type StorageChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volume        string                 `protobuf:"bytes,1,opt,name=volume,proto3" json:"volume,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Destructive   bool                   `protobuf:"varint,3,opt,name=destructive,proto3" json:"destructive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageChange) Reset() {
	*x = StorageChange{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageChange) ProtoMessage() {}

func (x *StorageChange) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageChange.ProtoReflect.Descriptor instead.
func (*StorageChange) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{14}
}

func (x *StorageChange) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *StorageChange) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *StorageChange) GetDestructive() bool {
	if x != nil {
		return x.Destructive
	}
	return false
}

type ResetVolumeRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Volume string                 `protobuf:"bytes,1,opt,name=volume,proto3" json:"volume,omitempty"`
	// The node's identity as the manifest renders it (JSON); the volume is created as it defines.
	Identity       string `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	FallbackSecret string `protobuf:"bytes,3,opt,name=fallback_secret,json=fallbackSecret,proto3" json:"fallback_secret,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResetVolumeRequest) Reset() {
	*x = ResetVolumeRequest{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetVolumeRequest) ProtoMessage() {}

func (x *ResetVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetVolumeRequest.ProtoReflect.Descriptor instead.
func (*ResetVolumeRequest) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{15}
}

func (x *ResetVolumeRequest) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *ResetVolumeRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *ResetVolumeRequest) GetFallbackSecret() string {
	if x != nil {
		return x.FallbackSecret
	}
	return ""
}

type ResetVolumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetVolumeResponse) Reset() {
	*x = ResetVolumeResponse{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetVolumeResponse) ProtoMessage() {}

func (x *ResetVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetVolumeResponse.ProtoReflect.Descriptor instead.
func (*ResetVolumeResponse) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{16}
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{17}
}

type StatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SHA-256 of the identity document the node runs, in lower-case hex.
	IdentityVersion string          `protobuf:"bytes,1,opt,name=identity_version,json=identityVersion,proto3" json:"identity_version,omitempty"`
	Disks           []*DiskStatus   `protobuf:"bytes,2,rep,name=disks,proto3" json:"disks,omitempty"`
	Volumes         []*VolumeStatus `protobuf:"bytes,3,rep,name=volumes,proto3" json:"volumes,omitempty"`
	FailedUnits     []string        `protobuf:"bytes,4,rep,name=failed_units,json=failedUnits,proto3" json:"failed_units,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{18}
}

func (x *StatusResponse) GetIdentityVersion() string {
	if x != nil {
		return x.IdentityVersion
	}
	return ""
}

func (x *StatusResponse) GetDisks() []*DiskStatus {
	if x != nil {
		return x.Disks
	}
	return nil
}

func (x *StatusResponse) GetVolumes() []*VolumeStatus {
	if x != nil {
		return x.Volumes
	}
	return nil
}

func (x *StatusResponse) GetFailedUnits() []string {
	if x != nil {
		return x.FailedUnits
	}
	return nil
}

type DiskStatus struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Name   string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Device string                 `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	// Why the disk's volumes could not be created or opened at boot; empty when they were.
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskStatus) Reset() {
	*x = DiskStatus{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskStatus) ProtoMessage() {}

func (x *DiskStatus) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskStatus.ProtoReflect.Descriptor instead.
func (*DiskStatus) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{19}
}

func (x *DiskStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DiskStatus) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *DiskStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type VolumeStatus struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Name       string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Disk       string                 `protobuf:"bytes,2,opt,name=disk,proto3" json:"disk,omitempty"`
	MountPoint string                 `protobuf:"bytes,3,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
	// Whether the volume's partition exists.
	Present bool `protobuf:"varint,4,opt,name=present,proto3" json:"present,omitempty"`
	// Whether the volume is mounted at its mount point.
	Mounted       bool `protobuf:"varint,5,opt,name=mounted,proto3" json:"mounted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeStatus) Reset() {
	*x = VolumeStatus{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeStatus) ProtoMessage() {}

func (x *VolumeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeStatus.ProtoReflect.Descriptor instead.
func (*VolumeStatus) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{20}
}

func (x *VolumeStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VolumeStatus) GetDisk() string {
	if x != nil {
		return x.Disk
	}
	return ""
}

func (x *VolumeStatus) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

func (x *VolumeStatus) GetPresent() bool {
	if x != nil {
		return x.Present
	}
	return false
}

func (x *VolumeStatus) GetMounted() bool {
	if x != nil {
		return x.Mounted
	}
	return false
}

type LogsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unit whose journal to stream; empty streams the whole boot.
	Unit string `protobuf:"bytes,1,opt,name=unit,proto3" json:"unit,omitempty"`
	// Keep streaming new entries until the client cancels.
	Follow        bool `protobuf:"varint,2,opt,name=follow,proto3" json:"follow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsRequest) Reset() {
	*x = LogsRequest{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsRequest) ProtoMessage() {}

func (x *LogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsRequest.ProtoReflect.Descriptor instead.
func (*LogsRequest) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{21}
}

func (x *LogsRequest) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *LogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

type LogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line          string                 `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsResponse) Reset() {
	*x = LogsResponse{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsResponse) ProtoMessage() {}

func (x *LogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsResponse.ProtoReflect.Descriptor instead.
func (*LogsResponse) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{22}
}

func (x *LogsResponse) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

type RebootRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebootRequest) Reset() {
	*x = RebootRequest{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebootRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebootRequest) ProtoMessage() {}

func (x *RebootRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebootRequest.ProtoReflect.Descriptor instead.
func (*RebootRequest) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{23}
}

type RebootResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebootResponse) Reset() {
	*x = RebootResponse{}
	mi := &file_chalkos_node_v1_node_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebootResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebootResponse) ProtoMessage() {}

func (x *RebootResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chalkos_node_v1_node_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebootResponse.ProtoReflect.Descriptor instead.
func (*RebootResponse) Descriptor() ([]byte, []int) {
	return file_chalkos_node_v1_node_proto_rawDescGZIP(), []int{24}
}

var File_chalkos_node_v1_node_proto protoreflect.FileDescriptor

const file_chalkos_node_v1_node_proto_rawDesc = "" +
	"\n" +
	"\x1achalkos/node/v1/node.proto\x12\x0fchalkos.node.v1\"\r\n" +
	"\vInfoRequest\"\xb7\x02\n" +
	"\fInfoResponse\x12)\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x15.chalkos.node.v1.ModeR\x04mode\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x19\n" +
	"\bimage_id\x18\x03 \x01(\tR\aimageId\x12\x1c\n" +
	"\tinstaller\x18\x04 \x01(\bR\tinstaller\x12\x1b\n" +
	"\tboot_disk\x18\x05 \x01(\tR\bbootDisk\x12\x10\n" +
	"\x03tpm\x18\x06 \x01(\bR\x03tpm\x12<\n" +
	"\vsecure_boot\x18\a \x01(\x0e2\x1b.chalkos.node.v1.SecureBootR\n" +
	"secureBoot\x12 \n" +
	"\vfingerprint\x18\b \x01(\tR\vfingerprint\x12\x1a\n" +
	"\bhostname\x18\t \x01(\tR\bhostname\"\x0e\n" +
	"\fDisksRequest\"<\n" +
	"\rDisksResponse\x12+\n" +
	"\x05disks\x18\x01 \x03(\v2\x15.chalkos.node.v1.DiskR\x05disks\"\x80\x02\n" +
	"\x04Disk\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06device\x18\x02 \x01(\tR\x06device\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x04R\x04size\x12\x16\n" +
	"\x06serial\x18\x05 \x01(\tR\x06serial\x12\x10\n" +
	"\x03wwn\x18\x06 \x01(\tR\x03wwn\x12\x12\n" +
	"\x04type\x18\a \x01(\tR\x04type\x12\x12\n" +
	"\x04path\x18\b \x01(\tR\x04path\x12:\n" +
	"\n" +
	"partitions\x18\t \x03(\v2\x1a.chalkos.node.v1.PartitionR\n" +
	"partitions\x12\x14\n" +
	"\x05usage\x18\n" +
	" \x01(\tR\x05usage\"\xa7\x01\n" +
	"\tPartition\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x16\n" +
	"\x06number\x18\x02 \x01(\rR\x06number\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x14\n" +
	"\x05label\x18\x05 \x01(\tR\x05label\x12\x12\n" +
	"\x04uuid\x18\x06 \x01(\tR\x04uuid\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\"\x8a\x01\n" +
	"\x0eInstallRequest\x128\n" +
	"\x06header\x18\x01 \x01(\v2\x1e.chalkos.node.v1.InstallHeaderH\x00R\x06header\x123\n" +
	"\x05chunk\x18\x02 \x01(\v2\x1b.chalkos.node.v1.ImageChunkH\x00R\x05chunkB\t\n" +
	"\amessage\"\xc3\x04\n" +
	"\rInstallHeader\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12)\n" +
	"\x10node_certificate\x18\x02 \x01(\fR\x0fnodeCertificate\x12\x19\n" +
	"\bnode_key\x18\x03 \x01(\fR\anodeKey\x12%\n" +
	"\x0eca_certificate\x18\x04 \x01(\fR\rcaCertificate\x12'\n" +
	"\x0ffallback_secret\x18\x05 \x01(\tR\x0efallbackSecret\x125\n" +
	"\bin_place\x18\x06 \x01(\v2\x18.chalkos.node.v1.InPlaceH\x00R\ainPlace\x124\n" +
	"\x04disk\x18\a \x01(\v2\x1e.chalkos.node.v1.DiskReferenceH\x00R\x04disk\x12\x1d\n" +
	"\n" +
	"image_size\x18\b \x01(\x04R\timageSize\x12!\n" +
	"\fimage_sha256\x18\t \x01(\fR\vimageSha256\x12\x1b\n" +
	"\twipe_disk\x18\n" +
	" \x01(\bR\bwipeDisk\x12d\n" +
	"\x12system_definitions\x18\v \x03(\v25.chalkos.node.v1.InstallHeader.SystemDefinitionsEntryR\x11systemDefinitions\x1aD\n" +
	"\x16SystemDefinitionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\b\n" +
	"\x06target\"\t\n" +
	"\aInPlace\"\x8b\x01\n" +
	"\rDiskReference\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x16\n" +
	"\x06serial\x18\x03 \x01(\tR\x06serial\x12\x10\n" +
	"\x03wwn\x18\x04 \x01(\tR\x03wwn\x12\x12\n" +
	"\x04size\x18\x05 \x01(\tR\x04size\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\" \n" +
	"\n" +
	"ImageChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x11\n" +
	"\x0fInstallResponse\"[\n" +
	"\x14ApplyIdentityRequest\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12'\n" +
	"\x0ffallback_secret\x18\x02 \x01(\tR\x0efallbackSecret\"z\n" +
	"\x15ApplyIdentityResponse\x128\n" +
	"\achanges\x18\x01 \x03(\v2\x1e.chalkos.node.v1.StorageChangeR\achanges\x12'\n" +
	"\x0frestarted_units\x18\x02 \x03(\tR\x0erestartedUnits\"a\n" +
	"\rStorageChange\x12\x16\n" +
	"\x06volume\x18\x01 \x01(\tR\x06volume\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12 \n" +
	"\vdestructive\x18\x03 \x01(\bR\vdestructive\"q\n" +
	"\x12ResetVolumeRequest\x12\x16\n" +
	"\x06volume\x18\x01 \x01(\tR\x06volume\x12\x1a\n" +
	"\bidentity\x18\x02 \x01(\tR\bidentity\x12'\n" +
	"\x0ffallback_secret\x18\x03 \x01(\tR\x0efallbackSecret\"\x15\n" +
	"\x13ResetVolumeResponse\"\x0f\n" +
	"\rStatusRequest\"\xca\x01\n" +
	"\x0eStatusResponse\x12)\n" +
	"\x10identity_version\x18\x01 \x01(\tR\x0fidentityVersion\x121\n" +
	"\x05disks\x18\x02 \x03(\v2\x1b.chalkos.node.v1.DiskStatusR\x05disks\x127\n" +
	"\avolumes\x18\x03 \x03(\v2\x1d.chalkos.node.v1.VolumeStatusR\avolumes\x12!\n" +
	"\ffailed_units\x18\x04 \x03(\tR\vfailedUnits\"N\n" +
	"\n" +
	"DiskStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06device\x18\x02 \x01(\tR\x06device\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x8b\x01\n" +
	"\fVolumeStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04disk\x18\x02 \x01(\tR\x04disk\x12\x1f\n" +
	"\vmount_point\x18\x03 \x01(\tR\n" +
	"mountPoint\x12\x18\n" +
	"\apresent\x18\x04 \x01(\bR\apresent\x12\x18\n" +
	"\amounted\x18\x05 \x01(\bR\amounted\"9\n" +
	"\vLogsRequest\x12\x12\n" +
	"\x04unit\x18\x01 \x01(\tR\x04unit\x12\x16\n" +
	"\x06follow\x18\x02 \x01(\bR\x06follow\"\"\n" +
	"\fLogsResponse\x12\x12\n" +
	"\x04line\x18\x01 \x01(\tR\x04line\"\x0f\n" +
	"\rRebootRequest\"\x10\n" +
	"\x0eRebootResponse*C\n" +
	"\x04Mode\x12\x14\n" +
	"\x10MODE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10MODE_MAINTENANCE\x10\x01\x12\x0f\n" +
	"\vMODE_NORMAL\x10\x02*x\n" +
	"\n" +
	"SecureBoot\x12\x1b\n" +
	"\x17SECURE_BOOT_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14SECURE_BOOT_DISABLED\x10\x01\x12\x17\n" +
	"\x13SECURE_BOOT_ENABLED\x10\x02\x12\x1a\n" +
	"\x16SECURE_BOOT_SETUP_MODE\x10\x032\x81\x05\n" +
	"\vNodeService\x12C\n" +
	"\x04Info\x12\x1c.chalkos.node.v1.InfoRequest\x1a\x1d.chalkos.node.v1.InfoResponse\x12F\n" +
	"\x05Disks\x12\x1d.chalkos.node.v1.DisksRequest\x1a\x1e.chalkos.node.v1.DisksResponse\x12N\n" +
	"\aInstall\x12\x1f.chalkos.node.v1.InstallRequest\x1a .chalkos.node.v1.InstallResponse(\x01\x12^\n" +
	"\rApplyIdentity\x12%.chalkos.node.v1.ApplyIdentityRequest\x1a&.chalkos.node.v1.ApplyIdentityResponse\x12X\n" +
	"\vResetVolume\x12#.chalkos.node.v1.ResetVolumeRequest\x1a$.chalkos.node.v1.ResetVolumeResponse\x12I\n" +
	"\x06Status\x12\x1e.chalkos.node.v1.StatusRequest\x1a\x1f.chalkos.node.v1.StatusResponse\x12E\n" +
	"\x04Logs\x12\x1c.chalkos.node.v1.LogsRequest\x1a\x1d.chalkos.node.v1.LogsResponse0\x01\x12I\n" +
	"\x06Reboot\x12\x1e.chalkos.node.v1.RebootRequest\x1a\x1f.chalkos.node.v1.RebootResponseB2Z0github.com/trevex/chalkos/pkg/api/node/v1;nodev1b\x06proto3"

var (
	file_chalkos_node_v1_node_proto_rawDescOnce sync.Once
	file_chalkos_node_v1_node_proto_rawDescData []byte
)

func file_chalkos_node_v1_node_proto_rawDescGZIP() []byte {
	file_chalkos_node_v1_node_proto_rawDescOnce.Do(func() {
		file_chalkos_node_v1_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chalkos_node_v1_node_proto_rawDesc), len(file_chalkos_node_v1_node_proto_rawDesc)))
	})
	return file_chalkos_node_v1_node_proto_rawDescData
}

var file_chalkos_node_v1_node_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_chalkos_node_v1_node_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_chalkos_node_v1_node_proto_goTypes = []any{
	(Mode)(0),                     // 0: chalkos.node.v1.Mode
	(SecureBoot)(0),               // 1: chalkos.node.v1.SecureBoot
	(*InfoRequest)(nil),           // 2: chalkos.node.v1.InfoRequest
	(*InfoResponse)(nil),          // 3: chalkos.node.v1.InfoResponse
	(*DisksRequest)(nil),          // 4: chalkos.node.v1.DisksRequest
	(*DisksResponse)(nil),         // 5: chalkos.node.v1.DisksResponse
	(*Disk)(nil),                  // 6: chalkos.node.v1.Disk
	(*Partition)(nil),             // 7: chalkos.node.v1.Partition
	(*InstallRequest)(nil),        // 8: chalkos.node.v1.InstallRequest
	(*InstallHeader)(nil),         // 9: chalkos.node.v1.InstallHeader
	(*InPlace)(nil),               // 10: chalkos.node.v1.InPlace
	(*DiskReference)(nil),         // 11: chalkos.node.v1.DiskReference
	(*ImageChunk)(nil),            // 12: chalkos.node.v1.ImageChunk
	(*InstallResponse)(nil),       // 13: chalkos.node.v1.InstallResponse
	(*ApplyIdentityRequest)(nil),  // 14: chalkos.node.v1.ApplyIdentityRequest
	(*ApplyIdentityResponse)(nil), // 15: chalkos.node.v1.ApplyIdentityResponse
	(*StorageChange)(nil),         // 16: chalkos.node.v1.StorageChange
	(*ResetVolumeRequest)(nil),    // 17: chalkos.node.v1.ResetVolumeRequest
	(*ResetVolumeResponse)(nil),   // 18: chalkos.node.v1.ResetVolumeResponse
	(*StatusRequest)(nil),         // 19: chalkos.node.v1.StatusRequest
	(*StatusResponse)(nil),        // 20: chalkos.node.v1.StatusResponse
	(*DiskStatus)(nil),            // 21: chalkos.node.v1.DiskStatus
	(*VolumeStatus)(nil),          // 22: chalkos.node.v1.VolumeStatus
	(*LogsRequest)(nil),           // 23: chalkos.node.v1.LogsRequest
	(*LogsResponse)(nil),          // 24: chalkos.node.v1.LogsResponse
	(*RebootRequest)(nil),         // 25: chalkos.node.v1.RebootRequest
	(*RebootResponse)(nil),        // 26: chalkos.node.v1.RebootResponse
	nil,                           // 27: chalkos.node.v1.InstallHeader.SystemDefinitionsEntry
}
var file_chalkos_node_v1_node_proto_depIdxs = []int32{
	0,  // 0: chalkos.node.v1.InfoResponse.mode:type_name -> chalkos.node.v1.Mode
	1,  // 1: chalkos.node.v1.InfoResponse.secure_boot:type_name -> chalkos.node.v1.SecureBoot
	6,  // 2: chalkos.node.v1.DisksResponse.disks:type_name -> chalkos.node.v1.Disk
	7,  // 3: chalkos.node.v1.Disk.partitions:type_name -> chalkos.node.v1.Partition
	9,  // 4: chalkos.node.v1.InstallRequest.header:type_name -> chalkos.node.v1.InstallHeader
	12, // 5: chalkos.node.v1.InstallRequest.chunk:type_name -> chalkos.node.v1.ImageChunk
	10, // 6: chalkos.node.v1.InstallHeader.in_place:type_name -> chalkos.node.v1.InPlace
	11, // 7: chalkos.node.v1.InstallHeader.disk:type_name -> chalkos.node.v1.DiskReference
	27, // 8: chalkos.node.v1.InstallHeader.system_definitions:type_name -> chalkos.node.v1.InstallHeader.SystemDefinitionsEntry
	16, // 9: chalkos.node.v1.ApplyIdentityResponse.changes:type_name -> chalkos.node.v1.StorageChange
	21, // 10: chalkos.node.v1.StatusResponse.disks:type_name -> chalkos.node.v1.DiskStatus
	22, // 11: chalkos.node.v1.StatusResponse.volumes:type_name -> chalkos.node.v1.VolumeStatus
	2,  // 12: chalkos.node.v1.NodeService.Info:input_type -> chalkos.node.v1.InfoRequest
	4,  // 13: chalkos.node.v1.NodeService.Disks:input_type -> chalkos.node.v1.DisksRequest
	8,  // 14: chalkos.node.v1.NodeService.Install:input_type -> chalkos.node.v1.InstallRequest
	14, // 15: chalkos.node.v1.NodeService.ApplyIdentity:input_type -> chalkos.node.v1.ApplyIdentityRequest
	17, // 16: chalkos.node.v1.NodeService.ResetVolume:input_type -> chalkos.node.v1.ResetVolumeRequest
	19, // 17: chalkos.node.v1.NodeService.Status:input_type -> chalkos.node.v1.StatusRequest
	23, // 18: chalkos.node.v1.NodeService.Logs:input_type -> chalkos.node.v1.LogsRequest
	25, // 19: chalkos.node.v1.NodeService.Reboot:input_type -> chalkos.node.v1.RebootRequest
	3,  // 20: chalkos.node.v1.NodeService.Info:output_type -> chalkos.node.v1.InfoResponse
	5,  // 21: chalkos.node.v1.NodeService.Disks:output_type -> chalkos.node.v1.DisksResponse
	13, // 22: chalkos.node.v1.NodeService.Install:output_type -> chalkos.node.v1.InstallResponse
	15, // 23: chalkos.node.v1.NodeService.ApplyIdentity:output_type -> chalkos.node.v1.ApplyIdentityResponse
	18, // 24: chalkos.node.v1.NodeService.ResetVolume:output_type -> chalkos.node.v1.ResetVolumeResponse
	20, // 25: chalkos.node.v1.NodeService.Status:output_type -> chalkos.node.v1.StatusResponse
	24, // 26: chalkos.node.v1.NodeService.Logs:output_type -> chalkos.node.v1.LogsResponse
	26, // 27: chalkos.node.v1.NodeService.Reboot:output_type -> chalkos.node.v1.RebootResponse
	20, // [20:28] is the sub-list for method output_type
	12, // [12:20] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_chalkos_node_v1_node_proto_init() }
func file_chalkos_node_v1_node_proto_init() {
	if File_chalkos_node_v1_node_proto != nil {
		return
	}
	file_chalkos_node_v1_node_proto_msgTypes[6].OneofWrappers = []any{
		(*InstallRequest_Header)(nil),
		(*InstallRequest_Chunk)(nil),
	}
	file_chalkos_node_v1_node_proto_msgTypes[7].OneofWrappers = []any{
		(*InstallHeader_InPlace)(nil),
		(*InstallHeader_Disk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chalkos_node_v1_node_proto_rawDesc), len(file_chalkos_node_v1_node_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chalkos_node_v1_node_proto_goTypes,
		DependencyIndexes: file_chalkos_node_v1_node_proto_depIdxs,
		EnumInfos:         file_chalkos_node_v1_node_proto_enumTypes,
		MessageInfos:      file_chalkos_node_v1_node_proto_msgTypes,
	}.Build()
	File_chalkos_node_v1_node_proto = out.File
	file_chalkos_node_v1_node_proto_goTypes = nil
	file_chalkos_node_v1_node_proto_depIdxs = nil
}
